export const CATEGORIES = [
  {
    key: 'bread',
    label: 'Bread & Bakery',
    emoji: '🍞',
    items: [
      { name: 'White Sandwich Bread', search_hint: 'white sandwich bread', is_branded: false },
      { name: 'Whole Wheat Bread', search_hint: 'whole wheat bread', is_branded: false },
      { name: 'Sourdough Bread', search_hint: 'sourdough bread', is_branded: false },
      { name: 'Multigrain Bread', search_hint: 'multigrain bread', is_branded: false },
      { name: 'English Muffins', search_hint: 'english muffins', is_branded: false },
      { name: 'Bagels', search_hint: 'bagels', is_branded: false },
      { name: 'Hamburger Buns', search_hint: 'hamburger buns', is_branded: false },
      { name: 'Hot Dog Buns', search_hint: 'hot dog buns', is_branded: false },
      { name: 'Dinner Rolls', search_hint: 'dinner rolls', is_branded: false },
      { name: 'Tortillas', search_hint: 'flour tortillas', is_branded: false },
      { name: 'Pita Bread', search_hint: 'pita bread', is_branded: false },
      { name: 'Dave\'s Killer Bread', search_hint: "Dave's Killer Bread whole wheat", is_branded: true },
      { name: 'Nature\'s Own Bread', search_hint: "Nature's Own bread", is_branded: true },
      { name: 'Arnold Bread', search_hint: 'Arnold bread whole grain', is_branded: true },
    ],
  },
  {
    key: 'eggs_dairy',
    label: 'Eggs & Dairy',
    emoji: '🥚',
    items: [
      { name: 'Large Eggs (12 ct)', search_hint: 'large eggs dozen', is_branded: false },
      { name: 'Extra Large Eggs (18 ct)', search_hint: 'extra large eggs 18', is_branded: false },
      { name: 'Cage-Free Eggs', search_hint: 'cage free eggs', is_branded: false },
      { name: 'Organic Eggs', search_hint: 'organic eggs', is_branded: false },
      { name: 'Egg Whites (carton)', search_hint: 'egg whites carton', is_branded: false },
      { name: 'Whole Milk (1 gallon)', search_hint: 'whole milk gallon', is_branded: false },
      { name: '2% Milk (1 gallon)', search_hint: '2% reduced fat milk gallon', is_branded: false },
      { name: 'Skim Milk', search_hint: 'skim milk gallon', is_branded: false },
      { name: 'Almond Milk', search_hint: 'almond milk unsweetened', is_branded: false },
      { name: 'Oat Milk', search_hint: 'oat milk', is_branded: false },
      { name: 'Heavy Cream', search_hint: 'heavy whipping cream', is_branded: false },
      { name: 'Half & Half', search_hint: 'half and half', is_branded: false },
      { name: 'Sour Cream', search_hint: 'sour cream', is_branded: false },
      { name: 'Daisy Sour Cream', search_hint: 'Daisy sour cream', is_branded: true },
      { name: 'Horizon Organic Milk', search_hint: 'Horizon organic milk', is_branded: true },
    ],
  },
  {
    key: 'cheese',
    label: 'Cheese',
    emoji: '🧀',
    items: [
      { name: 'Shredded Cheddar', search_hint: 'shredded cheddar cheese', is_branded: false },
      { name: 'Shredded Mozzarella', search_hint: 'shredded mozzarella cheese', is_branded: false },
      { name: 'Sliced American Cheese', search_hint: 'american cheese slices', is_branded: false },
      { name: 'Sliced Swiss Cheese', search_hint: 'swiss cheese slices', is_branded: false },
      { name: 'Cream Cheese', search_hint: 'cream cheese block', is_branded: false },
      { name: 'Parmesan (shredded)', search_hint: 'shredded parmesan cheese', is_branded: false },
      { name: 'Cottage Cheese', search_hint: 'cottage cheese', is_branded: false },
      { name: 'Ricotta Cheese', search_hint: 'ricotta cheese', is_branded: false },
      { name: 'Colby Jack Cheese', search_hint: 'colby jack cheese shredded', is_branded: false },
      { name: 'Kraft Singles', search_hint: 'Kraft Singles american cheese', is_branded: true },
      { name: 'Philadelphia Cream Cheese', search_hint: 'Philadelphia cream cheese', is_branded: true },
      { name: 'Sargento Shredded', search_hint: 'Sargento shredded cheese', is_branded: true },
      { name: 'Tillamook Cheddar', search_hint: 'Tillamook cheddar cheese', is_branded: true },
    ],
  },
  {
    key: 'meat',
    label: 'Meat & Poultry',
    emoji: '🥩',
    items: [
      { name: 'Ground Beef (80/20)', search_hint: 'ground beef 80/20 1 lb', is_branded: false },
      { name: 'Ground Turkey', search_hint: 'ground turkey 1 lb', is_branded: false },
      { name: 'Chicken Breast (boneless)', search_hint: 'boneless skinless chicken breast', is_branded: false },
      { name: 'Chicken Thighs', search_hint: 'boneless skinless chicken thighs', is_branded: false },
      { name: 'Whole Chicken', search_hint: 'whole chicken', is_branded: false },
      { name: 'Pork Chops', search_hint: 'pork chops boneless', is_branded: false },
      { name: 'Pork Tenderloin', search_hint: 'pork tenderloin', is_branded: false },
      { name: 'Baby Back Ribs', search_hint: 'pork baby back ribs', is_branded: false },
      { name: 'Bacon', search_hint: 'bacon sliced', is_branded: false },
      { name: 'Hot Dogs', search_hint: 'beef hot dogs', is_branded: false },
      { name: 'Steak (ribeye)', search_hint: 'ribeye steak', is_branded: false },
      { name: 'Salmon Fillet', search_hint: 'salmon fillet', is_branded: false },
      { name: 'Shrimp (frozen)', search_hint: 'frozen shrimp peeled deveined', is_branded: false },
      { name: 'Oscar Mayer Bacon', search_hint: 'Oscar Mayer bacon', is_branded: true },
      { name: 'Jennie-O Ground Turkey', search_hint: 'Jennie-O ground turkey', is_branded: true },
      { name: 'Ball Park Hot Dogs', search_hint: 'Ball Park beef hot dogs', is_branded: true },
    ],
  },
  {
    key: 'produce',
    label: 'Fruits & Vegetables',
    emoji: '🥦',
    items: [
      { name: 'Bananas', search_hint: 'bananas bunch', is_branded: false },
      { name: 'Apples (Gala)', search_hint: 'Gala apples', is_branded: false },
      { name: 'Strawberries', search_hint: 'strawberries 1 lb', is_branded: false },
      { name: 'Blueberries', search_hint: 'blueberries pint', is_branded: false },
      { name: 'Avocados', search_hint: 'avocados', is_branded: false },
      { name: 'Tomatoes', search_hint: 'tomatoes on the vine', is_branded: false },
      { name: 'Broccoli', search_hint: 'broccoli crown', is_branded: false },
      { name: 'Spinach (bag)', search_hint: 'baby spinach bag', is_branded: false },
      { name: 'Romaine Lettuce', search_hint: 'romaine lettuce hearts', is_branded: false },
      { name: 'Baby Carrots', search_hint: 'baby carrots bag', is_branded: false },
      { name: 'Bell Peppers', search_hint: 'bell peppers', is_branded: false },
      { name: 'Yellow Onions', search_hint: 'yellow onions 3 lb bag', is_branded: false },
      { name: 'Russet Potatoes', search_hint: 'russet potatoes 5 lb bag', is_branded: false },
      { name: 'Sweet Potatoes', search_hint: 'sweet potatoes', is_branded: false },
      { name: 'Garlic', search_hint: 'garlic bulb', is_branded: false },
      { name: 'Lemons', search_hint: 'lemons bag', is_branded: false },
      { name: 'Limes', search_hint: 'limes bag', is_branded: false },
    ],
  },
  {
    key: 'cereal',
    label: 'Cereal & Breakfast',
    emoji: '🥣',
    items: [
      { name: 'Cheerios', search_hint: 'Cheerios cereal', is_branded: true },
      { name: 'Frosted Flakes', search_hint: "Kellogg's Frosted Flakes", is_branded: true },
      { name: 'Honey Bunches of Oats', search_hint: 'Honey Bunches of Oats cereal', is_branded: true },
      { name: 'Raisin Bran', search_hint: "Kellogg's Raisin Bran", is_branded: true },
      { name: 'Cocoa Puffs', search_hint: 'Cocoa Puffs cereal', is_branded: true },
      { name: 'Lucky Charms', search_hint: 'Lucky Charms cereal', is_branded: true },
      { name: 'Quaker Oats (old fashioned)', search_hint: 'Quaker old fashioned oats', is_branded: true },
      { name: 'Instant Oatmeal Packets', search_hint: 'Quaker instant oatmeal packets', is_branded: true },
      { name: 'Granola', search_hint: 'granola', is_branded: false },
      { name: 'Pancake Mix', search_hint: 'Bisquick pancake mix', is_branded: true },
      { name: 'Maple Syrup', search_hint: 'maple syrup pure', is_branded: false },
      { name: 'Pop-Tarts', search_hint: "Kellogg's Pop-Tarts", is_branded: true },
    ],
  },
  {
    key: 'snacks',
    label: 'Snacks & Chips',
    emoji: '🍿',
    items: [
      { name: 'Lay\'s Classic Chips', search_hint: "Lay's Classic potato chips", is_branded: true },
      { name: 'Doritos Nacho Cheese', search_hint: 'Doritos Nacho Cheese', is_branded: true },
      { name: 'Pringles', search_hint: 'Pringles original', is_branded: true },
      { name: 'Cheez-Its', search_hint: 'Cheez-It crackers original', is_branded: true },
      { name: 'Goldfish Crackers', search_hint: 'Pepperidge Farm Goldfish crackers', is_branded: true },
      { name: 'Ritz Crackers', search_hint: 'Ritz crackers', is_branded: true },
      { name: 'Triscuits', search_hint: 'Triscuit crackers', is_branded: true },
      { name: 'Popcorn', search_hint: 'microwave popcorn', is_branded: false },
      { name: 'Pretzels', search_hint: 'pretzels', is_branded: false },
      { name: 'Trail Mix', search_hint: 'trail mix', is_branded: false },
      { name: 'Almonds', search_hint: 'almonds roasted', is_branded: false },
      { name: 'Cashews', search_hint: 'cashews', is_branded: false },
      { name: 'Peanuts', search_hint: 'peanuts roasted', is_branded: false },
      { name: 'Rice Cakes', search_hint: 'rice cakes', is_branded: false },
      { name: 'Fruit Snacks', search_hint: 'fruit snacks gummies', is_branded: false },
    ],
  },
  {
    key: 'cookies',
    label: 'Cookies & Sweets',
    emoji: '🍪',
    items: [
      { name: 'Oreos', search_hint: 'Oreo cookies', is_branded: true },
      { name: 'Chips Ahoy!', search_hint: 'Chips Ahoy cookies', is_branded: true },
      { name: 'Nutter Butter', search_hint: 'Nutter Butter cookies', is_branded: true },
      { name: 'Pepperidge Farm Milano', search_hint: 'Pepperidge Farm Milano cookies', is_branded: true },
      { name: 'Girl Scout Thin Mints', search_hint: 'Thin Mint cookies', is_branded: true },
      { name: 'Keebler Fudge Stripes', search_hint: 'Keebler Fudge Stripes cookies', is_branded: true },
      { name: 'Chocolate Chip Cookies', search_hint: 'chocolate chip cookies', is_branded: false },
      { name: 'Brownie Mix', search_hint: 'Betty Crocker brownie mix', is_branded: true },
      { name: 'Cake Mix', search_hint: 'Betty Crocker cake mix', is_branded: true },
      { name: 'Ice Cream (vanilla)', search_hint: 'vanilla ice cream half gallon', is_branded: false },
      { name: 'Breyers Ice Cream', search_hint: "Breyers ice cream", is_branded: true },
      { name: 'Häagen-Dazs Ice Cream', search_hint: 'Haagen-Dazs ice cream', is_branded: true },
      { name: 'Popsicles', search_hint: 'popsicles', is_branded: false },
    ],
  },
  {
    key: 'beverages',
    label: 'Beverages',
    emoji: '🥤',
    items: [
      { name: 'Coca-Cola (12 pk)', search_hint: 'Coca-Cola 12 pack cans', is_branded: true },
      { name: 'Pepsi (12 pk)', search_hint: 'Pepsi 12 pack cans', is_branded: true },
      { name: 'Sprite (12 pk)', search_hint: 'Sprite 12 pack cans', is_branded: true },
      { name: 'Dr Pepper (12 pk)', search_hint: 'Dr Pepper 12 pack cans', is_branded: true },
      { name: 'Gatorade', search_hint: 'Gatorade sports drink', is_branded: true },
      { name: 'Powerade', search_hint: 'Powerade sports drink', is_branded: true },
      { name: 'Orange Juice', search_hint: 'orange juice 52 oz', is_branded: false },
      { name: 'Tropicana OJ', search_hint: 'Tropicana orange juice', is_branded: true },
      { name: 'Apple Juice', search_hint: 'apple juice 64 oz', is_branded: false },
      { name: 'Water (24 pk)', search_hint: 'water bottles 24 pack', is_branded: false },
      { name: 'Sparkling Water', search_hint: 'LaCroix sparkling water', is_branded: true },
      { name: 'Coffee (ground)', search_hint: 'ground coffee', is_branded: false },
      { name: 'Folgers Coffee', search_hint: 'Folgers ground coffee', is_branded: true },
      { name: 'Starbucks Coffee', search_hint: 'Starbucks ground coffee', is_branded: true },
      { name: 'Tea Bags', search_hint: 'Lipton tea bags', is_branded: true },
    ],
  },
  {
    key: 'canned',
    label: 'Canned & Pantry',
    emoji: '🥫',
    items: [
      { name: 'Canned Tomatoes (diced)', search_hint: 'diced tomatoes canned', is_branded: false },
      { name: 'Tomato Sauce', search_hint: 'tomato sauce canned', is_branded: false },
      { name: 'Tomato Paste', search_hint: 'tomato paste', is_branded: false },
      { name: 'Chicken Broth', search_hint: 'chicken broth 32 oz', is_branded: false },
      { name: 'Beef Broth', search_hint: 'beef broth 32 oz', is_branded: false },
      { name: 'Black Beans', search_hint: 'black beans canned', is_branded: false },
      { name: 'Kidney Beans', search_hint: 'kidney beans canned', is_branded: false },
      { name: 'Chickpeas', search_hint: 'chickpeas garbanzo beans canned', is_branded: false },
      { name: 'Canned Corn', search_hint: 'whole kernel corn canned', is_branded: false },
      { name: 'Canned Tuna', search_hint: 'tuna in water canned', is_branded: false },
      { name: 'Canned Salmon', search_hint: 'salmon canned', is_branded: false },
      { name: 'Peanut Butter', search_hint: 'peanut butter creamy', is_branded: false },
      { name: 'Jif Peanut Butter', search_hint: 'Jif peanut butter creamy', is_branded: true },
      { name: 'Skippy Peanut Butter', search_hint: 'Skippy peanut butter', is_branded: true },
      { name: 'Strawberry Jam', search_hint: 'strawberry jam', is_branded: false },
      { name: 'Honey', search_hint: 'honey pure', is_branded: false },
    ],
  },
  {
    key: 'pasta_rice',
    label: 'Pasta & Rice',
    emoji: '🍝',
    items: [
      { name: 'Spaghetti', search_hint: 'spaghetti pasta 16 oz', is_branded: false },
      { name: 'Penne Pasta', search_hint: 'penne pasta', is_branded: false },
      { name: 'Rotini Pasta', search_hint: 'rotini pasta', is_branded: false },
      { name: 'Elbow Macaroni', search_hint: 'elbow macaroni pasta', is_branded: false },
      { name: 'Fettuccine', search_hint: 'fettuccine pasta', is_branded: false },
      { name: 'White Rice (long grain)', search_hint: 'long grain white rice 5 lb', is_branded: false },
      { name: 'Brown Rice', search_hint: 'brown rice', is_branded: false },
      { name: 'Jasmine Rice', search_hint: 'jasmine rice', is_branded: false },
      { name: 'Pasta Sauce (marinara)', search_hint: 'marinara pasta sauce', is_branded: false },
      { name: 'Prego Pasta Sauce', search_hint: 'Prego pasta sauce', is_branded: true },
      { name: 'Ragu Pasta Sauce', search_hint: 'Ragu pasta sauce', is_branded: true },
      { name: 'Mac & Cheese (Kraft)', search_hint: 'Kraft mac and cheese', is_branded: true },
    ],
  },
  {
    key: 'frozen',
    label: 'Frozen Foods',
    emoji: '🧊',
    items: [
      { name: 'Frozen Pizza', search_hint: 'frozen pizza', is_branded: false },
      { name: 'DiGiorno Pizza', search_hint: 'DiGiorno frozen pizza', is_branded: true },
      { name: 'Frozen Chicken Nuggets', search_hint: 'frozen chicken nuggets', is_branded: false },
      { name: 'Frozen French Fries', search_hint: 'frozen french fries', is_branded: false },
      { name: 'Frozen Vegetables Mix', search_hint: 'frozen mixed vegetables', is_branded: false },
      { name: 'Frozen Broccoli', search_hint: 'frozen broccoli florets', is_branded: false },
      { name: 'Frozen Corn', search_hint: 'frozen sweet corn', is_branded: false },
      { name: 'Frozen Waffles', search_hint: 'Eggo frozen waffles', is_branded: true },
      { name: 'Frozen Burritos', search_hint: 'frozen burritos', is_branded: false },
      { name: 'Frozen Fish Sticks', search_hint: 'frozen fish sticks', is_branded: false },
      { name: 'Frozen Edamame', search_hint: 'frozen edamame', is_branded: false },
      { name: 'Lean Cuisine Meal', search_hint: 'Lean Cuisine frozen meal', is_branded: true },
      { name: 'Stouffer\'s Meal', search_hint: "Stouffer's frozen entree", is_branded: true },
    ],
  },
  {
    key: 'condiments',
    label: 'Condiments & Spices',
    emoji: '🧂',
    items: [
      { name: 'Ketchup', search_hint: 'ketchup', is_branded: false },
      { name: 'Heinz Ketchup', search_hint: 'Heinz ketchup', is_branded: true },
      { name: 'Yellow Mustard', search_hint: 'yellow mustard', is_branded: false },
      { name: 'Mayonnaise', search_hint: 'mayonnaise', is_branded: false },
      { name: 'Hellmann\'s Mayonnaise', search_hint: "Hellmann's mayonnaise", is_branded: true },
      { name: 'Ranch Dressing', search_hint: 'Hidden Valley ranch dressing', is_branded: true },
      { name: 'Hot Sauce', search_hint: 'Frank\'s RedHot hot sauce', is_branded: true },
      { name: 'Sriracha', search_hint: 'Huy Fong sriracha', is_branded: true },
      { name: 'Soy Sauce', search_hint: 'soy sauce', is_branded: false },
      { name: 'Olive Oil', search_hint: 'extra virgin olive oil', is_branded: false },
      { name: 'Vegetable Oil', search_hint: 'vegetable oil', is_branded: false },
      { name: 'Salt', search_hint: 'Morton iodized salt', is_branded: true },
      { name: 'Black Pepper', search_hint: 'ground black pepper', is_branded: false },
      { name: 'Garlic Powder', search_hint: 'garlic powder', is_branded: false },
      { name: 'Italian Seasoning', search_hint: 'Italian seasoning', is_branded: false },
    ],
  },
  {
    key: 'cleaning',
    label: 'Cleaning & Paper',
    emoji: '🧹',
    items: [
      { name: 'Paper Towels', search_hint: 'paper towels', is_branded: false },
      { name: 'Bounty Paper Towels', search_hint: 'Bounty paper towels', is_branded: true },
      { name: 'Toilet Paper', search_hint: 'toilet paper', is_branded: false },
      { name: 'Charmin Toilet Paper', search_hint: 'Charmin toilet paper', is_branded: true },
      { name: 'Dish Soap', search_hint: 'dish soap', is_branded: false },
      { name: 'Dawn Dish Soap', search_hint: 'Dawn dish soap', is_branded: true },
      { name: 'Laundry Detergent', search_hint: 'laundry detergent', is_branded: false },
      { name: 'Tide Pods', search_hint: 'Tide Pods laundry detergent', is_branded: true },
      { name: 'All-Purpose Cleaner', search_hint: 'all purpose cleaner spray', is_branded: false },
      { name: 'Windex Glass Cleaner', search_hint: 'Windex glass cleaner', is_branded: true },
      { name: 'Trash Bags', search_hint: 'trash bags 13 gallon', is_branded: false },
      { name: 'Ziploc Bags', search_hint: 'Ziploc storage bags gallon', is_branded: true },
      { name: 'Aluminum Foil', search_hint: 'Reynolds aluminum foil', is_branded: true },
      { name: 'Plastic Wrap', search_hint: 'plastic wrap', is_branded: false },
    ],
  },
  {
    key: 'personal_care',
    label: 'Personal Care',
    emoji: '🧴',
    items: [
      { name: 'Shampoo', search_hint: 'shampoo', is_branded: false },
      { name: 'Head & Shoulders', search_hint: 'Head and Shoulders shampoo', is_branded: true },
      { name: 'Conditioner', search_hint: 'conditioner hair', is_branded: false },
      { name: 'Body Wash', search_hint: 'body wash', is_branded: false },
      { name: 'Dove Body Wash', search_hint: 'Dove body wash', is_branded: true },
      { name: 'Bar Soap', search_hint: 'bar soap', is_branded: false },
      { name: 'Deodorant', search_hint: 'deodorant antiperspirant', is_branded: false },
      { name: 'Old Spice Deodorant', search_hint: 'Old Spice deodorant', is_branded: true },
      { name: 'Toothpaste', search_hint: 'toothpaste', is_branded: false },
      { name: 'Colgate Toothpaste', search_hint: 'Colgate toothpaste', is_branded: true },
      { name: 'Mouthwash', search_hint: 'Listerine mouthwash', is_branded: true },
      { name: 'Razor Blades', search_hint: 'razor blades refill', is_branded: false },
      { name: 'Gillette Razors', search_hint: 'Gillette razor', is_branded: true },
    ],
  },
];

export const BRANDS = [
  { key: 'coca_cola', label: 'Coca-Cola', emoji: '🥤', search: 'Coca-Cola' },
  { key: 'pepsi', label: 'Pepsi', emoji: '🥤', search: 'Pepsi' },
  { key: 'sprite', label: 'Sprite', emoji: '🥤', search: 'Sprite' },
  { key: 'dr_pepper', label: 'Dr Pepper', emoji: '🥤', search: 'Dr Pepper' },
  { key: 'kelloggs', label: "Kellogg's", emoji: '🥣', search: "Kellogg's cereal" },
  { key: 'general_mills', label: 'General Mills', emoji: '🥣', search: 'General Mills cereal' },
  { key: 'quaker', label: 'Quaker', emoji: '🥣', search: 'Quaker oats' },
  { key: 'oreo', label: 'Oreo', emoji: '🍪', search: 'Oreo cookies' },
  { key: 'chips_ahoy', label: 'Chips Ahoy', emoji: '🍪', search: 'Chips Ahoy cookies' },
  { key: 'lays', label: "Lay's", emoji: '🥔', search: "Lay's chips" },
  { key: 'doritos', label: 'Doritos', emoji: '🌽', search: 'Doritos' },
  { key: 'pringles', label: 'Pringles', emoji: '🥫', search: 'Pringles' },
  { key: 'kraft', label: 'Kraft', emoji: '🧀', search: 'Kraft cheese' },
  { key: 'philadelphia', label: 'Philadelphia', emoji: '🧀', search: 'Philadelphia cream cheese' },
  { key: 'oscar_mayer', label: 'Oscar Mayer', emoji: '🥓', search: 'Oscar Mayer' },
  { key: 'tyson', label: 'Tyson', emoji: '🍗', search: 'Tyson chicken' },
  { key: 'birds_eye', label: "Bird's Eye", emoji: '🥦', search: "Bird's Eye frozen vegetables" },
  { key: 'jif', label: 'Jif', emoji: '🥜', search: 'Jif peanut butter' },
  { key: 'heinz', label: 'Heinz', emoji: '🍅', search: 'Heinz ketchup' },
  { key: 'hellmanns', label: "Hellmann's", emoji: '🥗', search: "Hellmann's mayonnaise" },
  { key: 'hidden_valley', label: 'Hidden Valley', emoji: '🥗', search: 'Hidden Valley ranch' },
  { key: 'hunts', label: "Hunt's", emoji: '🍅', search: "Hunt's tomato sauce" },
  { key: 'prego', label: 'Prego', emoji: '🍝', search: 'Prego pasta sauce' },
  { key: 'ragu', label: 'Ragú', emoji: '🍝', search: 'Ragu pasta sauce' },
  { key: 'campbell', label: "Campbell's", emoji: '🥫', search: "Campbell's soup" },
  { key: 'tide', label: 'Tide', emoji: '🧺', search: 'Tide laundry detergent' },
  { key: 'dawn', label: 'Dawn', emoji: '🫧', search: 'Dawn dish soap' },
  { key: 'bounty', label: 'Bounty', emoji: '🧻', search: 'Bounty paper towels' },
  { key: 'charmin', label: 'Charmin', emoji: '🧻', search: 'Charmin toilet paper' },
  { key: 'dove', label: 'Dove', emoji: '🧴', search: 'Dove soap' },
  { key: 'colgate', label: 'Colgate', emoji: '🦷', search: 'Colgate toothpaste' },
  { key: 'gillette', label: 'Gillette', emoji: '🪒', search: 'Gillette razor' },
];