export const CATEGORIES = [
  // ── PRODUCE ─────────────────────────────────────────────────────────────
  {
    key: 'produce',
    label: 'Fruits & Vegetables',
    emoji: '🥦',
    items: [
      { name: 'Bananas', search_hint: 'bananas bunch', is_branded: false },
      { name: 'Apples (Gala)', search_hint: 'Gala apples', is_branded: false },
      { name: 'Apples (Honeycrisp)', search_hint: 'Honeycrisp apples', is_branded: false },
      { name: 'Grapes (Red Seedless)', search_hint: 'red seedless grapes', is_branded: false },
      { name: 'Grapes (Green)', search_hint: 'green seedless grapes', is_branded: false },
      { name: 'Strawberries', search_hint: 'strawberries 1 lb', is_branded: false },
      { name: 'Blueberries', search_hint: 'blueberries pint', is_branded: false },
      { name: 'Raspberries', search_hint: 'raspberries 6 oz', is_branded: false },
      { name: 'Blackberries', search_hint: 'blackberries 6 oz', is_branded: false },
      { name: 'Oranges', search_hint: 'navel oranges bag', is_branded: false },
      { name: 'Clementines', search_hint: 'clementines bag', is_branded: false },
      { name: 'Lemons', search_hint: 'lemons bag', is_branded: false },
      { name: 'Limes', search_hint: 'limes bag', is_branded: false },
      { name: 'Peaches', search_hint: 'peaches', is_branded: false },
      { name: 'Pears', search_hint: 'Bartlett pears', is_branded: false },
      { name: 'Pineapple', search_hint: 'whole pineapple', is_branded: false },
      { name: 'Watermelon', search_hint: 'seedless watermelon', is_branded: false },
      { name: 'Cantaloupe', search_hint: 'cantaloupe', is_branded: false },
      { name: 'Mango', search_hint: 'mango', is_branded: false },
      { name: 'Avocados', search_hint: 'avocados', is_branded: false },
      { name: 'Tomatoes (vine)', search_hint: 'tomatoes on the vine', is_branded: false },
      { name: 'Roma Tomatoes', search_hint: 'Roma tomatoes', is_branded: false },
      { name: 'Cherry Tomatoes', search_hint: 'cherry tomatoes pint', is_branded: false },
      { name: 'Broccoli', search_hint: 'broccoli crown', is_branded: false },
      { name: 'Cauliflower', search_hint: 'cauliflower head', is_branded: false },
      { name: 'Spinach (bag)', search_hint: 'baby spinach bag', is_branded: false },
      { name: 'Romaine Lettuce', search_hint: 'romaine lettuce hearts', is_branded: false },
      { name: 'Iceberg Lettuce', search_hint: 'iceberg lettuce head', is_branded: false },
      { name: 'Spring Mix Salad', search_hint: 'spring mix salad greens', is_branded: false },
      { name: 'Kale', search_hint: 'kale bunch', is_branded: false },
      { name: 'Baby Carrots', search_hint: 'baby carrots bag', is_branded: false },
      { name: 'Carrots (whole)', search_hint: 'carrots 2 lb bag', is_branded: false },
      { name: 'Celery', search_hint: 'celery stalks', is_branded: false },
      { name: 'Bell Peppers', search_hint: 'bell peppers', is_branded: false },
      { name: 'Jalapeños', search_hint: 'jalapeno peppers', is_branded: false },
      { name: 'Cucumber', search_hint: 'cucumber', is_branded: false },
      { name: 'Zucchini', search_hint: 'zucchini squash', is_branded: false },
      { name: 'Yellow Squash', search_hint: 'yellow squash', is_branded: false },
      { name: 'Yellow Onions', search_hint: 'yellow onions 3 lb bag', is_branded: false },
      { name: 'Red Onions', search_hint: 'red onions', is_branded: false },
      { name: 'Green Onions', search_hint: 'green onions scallions', is_branded: false },
      { name: 'Garlic', search_hint: 'garlic bulb', is_branded: false },
      { name: 'Russet Potatoes', search_hint: 'russet potatoes 5 lb bag', is_branded: false },
      { name: 'Sweet Potatoes', search_hint: 'sweet potatoes', is_branded: false },
      { name: 'Baby Potatoes', search_hint: 'baby yellow potatoes', is_branded: false },
      { name: 'Corn on the Cob', search_hint: 'corn on the cob', is_branded: false },
      { name: 'Mushrooms', search_hint: 'mushrooms white button', is_branded: false },
      { name: 'Asparagus', search_hint: 'asparagus bunch', is_branded: false },
      { name: 'Brussels Sprouts', search_hint: 'Brussels sprouts', is_branded: false },
      { name: 'Green Beans', search_hint: 'fresh green beans', is_branded: false },
    ],
  },

  // ── BREAD & BAKERY ────────────────────────────────────────────────────
  {
    key: 'bread',
    label: 'Bread & Bakery',
    emoji: '🍞',
    items: [
      { name: 'White Sandwich Bread', search_hint: 'white sandwich bread loaf', is_branded: false },
      { name: 'Whole Wheat Bread', search_hint: 'whole wheat bread', is_branded: false },
      { name: 'Sourdough Bread', search_hint: 'sourdough bread loaf', is_branded: false },
      { name: 'Multigrain Bread', search_hint: 'multigrain bread', is_branded: false },
      { name: 'Rye Bread', search_hint: 'rye bread', is_branded: false },
      { name: 'Gluten-Free Bread', search_hint: 'gluten free bread', is_branded: false },
      { name: 'English Muffins', search_hint: 'english muffins', is_branded: false },
      { name: 'Bagels', search_hint: 'bagels', is_branded: false },
      { name: 'Hamburger Buns', search_hint: 'hamburger buns 8 ct', is_branded: false },
      { name: 'Hot Dog Buns', search_hint: 'hot dog buns 8 ct', is_branded: false },
      { name: 'Dinner Rolls', search_hint: 'dinner rolls', is_branded: false },
      { name: 'Flour Tortillas', search_hint: 'flour tortillas 10 inch', is_branded: false },
      { name: 'Corn Tortillas', search_hint: 'corn tortillas', is_branded: false },
      { name: 'Pita Bread', search_hint: 'pita bread', is_branded: false },
      { name: 'Croissants', search_hint: 'croissants bakery', is_branded: false },
      { name: 'Muffins', search_hint: 'bakery muffins', is_branded: false },
      { name: 'Cinnamon Rolls', search_hint: 'Pillsbury cinnamon rolls', is_branded: true },
      { name: "Dave's Killer Bread", search_hint: "Dave's Killer Bread whole wheat", is_branded: true },
      { name: "Nature's Own Bread", search_hint: "Nature's Own bread", is_branded: true },
      { name: 'Arnold Bread', search_hint: 'Arnold bread whole grain', is_branded: true },
      { name: 'Mission Flour Tortillas', search_hint: 'Mission flour tortillas', is_branded: true },
      { name: 'Sara Lee Bread', search_hint: 'Sara Lee bread', is_branded: true },
    ],
  },

  // ── EGGS & DAIRY ──────────────────────────────────────────────────────
  {
    key: 'eggs_dairy',
    label: 'Eggs & Dairy',
    emoji: '🥚',
    items: [
      { name: 'Large Eggs (12 ct)', search_hint: 'large eggs dozen', is_branded: false },
      { name: 'Extra Large Eggs (18 ct)', search_hint: 'extra large eggs 18', is_branded: false },
      { name: 'Cage-Free Eggs', search_hint: 'cage free eggs', is_branded: false },
      { name: 'Organic Eggs', search_hint: 'organic eggs', is_branded: false },
      { name: 'Egg Whites (carton)', search_hint: 'egg whites liquid carton', is_branded: false },
      { name: 'Whole Milk (gallon)', search_hint: 'whole milk gallon', is_branded: false },
      { name: '2% Milk (gallon)', search_hint: '2% reduced fat milk gallon', is_branded: false },
      { name: 'Skim Milk', search_hint: 'skim milk gallon', is_branded: false },
      { name: 'Almond Milk', search_hint: 'almond milk unsweetened', is_branded: false },
      { name: 'Oat Milk', search_hint: 'oat milk original', is_branded: false },
      { name: 'Soy Milk', search_hint: 'soy milk', is_branded: false },
      { name: 'Coconut Milk (carton)', search_hint: 'coconut milk beverage carton', is_branded: false },
      { name: 'Heavy Cream', search_hint: 'heavy whipping cream pint', is_branded: false },
      { name: 'Half & Half', search_hint: 'half and half pint', is_branded: false },
      { name: 'Sour Cream', search_hint: 'sour cream', is_branded: false },
      { name: 'Greek Yogurt (plain)', search_hint: 'plain Greek yogurt', is_branded: false },
      { name: 'Strawberry Yogurt', search_hint: 'strawberry yogurt', is_branded: false },
      { name: 'Butter (salted)', search_hint: 'salted butter 4 sticks', is_branded: false },
      { name: 'Butter (unsalted)', search_hint: 'unsalted butter', is_branded: false },
      { name: 'Margarine', search_hint: 'margarine spread', is_branded: false },
      { name: 'Daisy Sour Cream', search_hint: 'Daisy sour cream', is_branded: true },
      { name: 'Horizon Organic Milk', search_hint: 'Horizon organic milk', is_branded: true },
      { name: 'Chobani Greek Yogurt', search_hint: 'Chobani Greek yogurt', is_branded: true },
      { name: 'Fage Greek Yogurt', search_hint: 'Fage Greek yogurt', is_branded: true },
      { name: 'Oatly Oat Milk', search_hint: 'Oatly oat milk', is_branded: true },
      { name: 'Land O Lakes Butter', search_hint: 'Land O Lakes butter', is_branded: true },
    ],
  },

  // ── CHEESE ────────────────────────────────────────────────────────────
  {
    key: 'cheese',
    label: 'Cheese',
    emoji: '🧀',
    items: [
      { name: 'Shredded Cheddar', search_hint: 'shredded cheddar cheese 8 oz', is_branded: false },
      { name: 'Shredded Mozzarella', search_hint: 'shredded mozzarella cheese 8 oz', is_branded: false },
      { name: 'Shredded Mexican Blend', search_hint: 'Mexican blend shredded cheese', is_branded: false },
      { name: 'Shredded Parmesan', search_hint: 'shredded parmesan cheese', is_branded: false },
      { name: 'Sliced American Cheese', search_hint: 'american cheese slices', is_branded: false },
      { name: 'Sliced Swiss Cheese', search_hint: 'swiss cheese slices', is_branded: false },
      { name: 'Sliced Provolone', search_hint: 'provolone cheese slices', is_branded: false },
      { name: 'Cream Cheese (block)', search_hint: 'cream cheese 8 oz block', is_branded: false },
      { name: 'Cottage Cheese', search_hint: 'cottage cheese 16 oz', is_branded: false },
      { name: 'Ricotta Cheese', search_hint: 'ricotta cheese 15 oz', is_branded: false },
      { name: 'Colby Jack Cheese', search_hint: 'colby jack cheese block', is_branded: false },
      { name: 'Pepper Jack Cheese', search_hint: 'pepper jack cheese', is_branded: false },
      { name: 'String Cheese', search_hint: 'string cheese mozzarella sticks', is_branded: false },
      { name: 'Feta Cheese', search_hint: 'feta cheese crumbled', is_branded: false },
      { name: 'Brie', search_hint: 'brie cheese wheel', is_branded: false },
      { name: 'Kraft Singles', search_hint: 'Kraft Singles american cheese', is_branded: true },
      { name: 'Philadelphia Cream Cheese', search_hint: 'Philadelphia cream cheese', is_branded: true },
      { name: 'Sargento Shredded', search_hint: 'Sargento shredded cheddar', is_branded: true },
      { name: 'Tillamook Cheddar', search_hint: 'Tillamook sharp cheddar', is_branded: true },
      { name: 'BabyBel Cheese', search_hint: 'Mini BabyBel cheese snack', is_branded: true },
    ],
  },

  // ── MEAT & POULTRY ───────────────────────────────────────────────────
  {
    key: 'meat',
    label: 'Meat & Poultry',
    emoji: '🥩',
    items: [
      { name: 'Ground Beef (80/20)', search_hint: 'ground beef 80/20 1 lb', is_branded: false },
      { name: 'Ground Beef (93% lean)', search_hint: 'lean ground beef 93% 1 lb', is_branded: false },
      { name: 'Ground Turkey', search_hint: 'ground turkey 93% lean 1 lb', is_branded: false },
      { name: 'Ground Pork', search_hint: 'ground pork 1 lb', is_branded: false },
      { name: 'Chicken Breast (boneless)', search_hint: 'boneless skinless chicken breast', is_branded: false },
      { name: 'Chicken Thighs', search_hint: 'boneless skinless chicken thighs', is_branded: false },
      { name: 'Chicken Drumsticks', search_hint: 'chicken drumsticks', is_branded: false },
      { name: 'Whole Chicken', search_hint: 'whole chicken', is_branded: false },
      { name: 'Chicken Wings', search_hint: 'chicken wings', is_branded: false },
      { name: 'Pork Chops (boneless)', search_hint: 'boneless pork chops', is_branded: false },
      { name: 'Pork Tenderloin', search_hint: 'pork tenderloin', is_branded: false },
      { name: 'Baby Back Ribs', search_hint: 'pork baby back ribs rack', is_branded: false },
      { name: 'Pork Sausage', search_hint: 'pork breakfast sausage roll', is_branded: false },
      { name: 'Italian Sausage', search_hint: 'Italian sausage links', is_branded: false },
      { name: 'Bacon', search_hint: 'bacon sliced 16 oz', is_branded: false },
      { name: 'Turkey Bacon', search_hint: 'turkey bacon', is_branded: false },
      { name: 'Hot Dogs', search_hint: 'beef hot dogs', is_branded: false },
      { name: 'Deli Ham', search_hint: 'deli sliced ham', is_branded: false },
      { name: 'Deli Turkey', search_hint: 'deli sliced turkey breast', is_branded: false },
      { name: 'Ribeye Steak', search_hint: 'ribeye steak', is_branded: false },
      { name: 'NY Strip Steak', search_hint: 'New York strip steak', is_branded: false },
      { name: 'Salmon Fillet', search_hint: 'Atlantic salmon fillet', is_branded: false },
      { name: 'Tilapia Fillet', search_hint: 'tilapia fillet fresh', is_branded: false },
      { name: 'Shrimp (frozen)', search_hint: 'frozen shrimp peeled deveined', is_branded: false },
      { name: 'Oscar Mayer Bacon', search_hint: 'Oscar Mayer bacon', is_branded: true },
      { name: 'Jennie-O Ground Turkey', search_hint: 'Jennie-O ground turkey', is_branded: true },
      { name: 'Ball Park Hot Dogs', search_hint: 'Ball Park beef hot dogs', is_branded: true },
      { name: 'Tyson Chicken Breasts', search_hint: 'Tyson boneless chicken breasts', is_branded: true },
      { name: 'Hillshire Farm Sausage', search_hint: 'Hillshire Farm smoked sausage', is_branded: true },
    ],
  },

  // ── SEAFOOD ───────────────────────────────────────────────────────────
  {
    key: 'seafood',
    label: 'Seafood',
    emoji: '🦐',
    items: [
      { name: 'Atlantic Salmon', search_hint: 'Atlantic salmon fillet fresh', is_branded: false },
      { name: 'Tilapia', search_hint: 'tilapia fillet', is_branded: false },
      { name: 'Cod Fillet', search_hint: 'cod fish fillet', is_branded: false },
      { name: 'Tuna Steak', search_hint: 'fresh tuna steak', is_branded: false },
      { name: 'Mahi-Mahi', search_hint: 'mahi mahi fillet', is_branded: false },
      { name: 'Shrimp (large, frozen)', search_hint: 'large frozen shrimp 16-20 count', is_branded: false },
      { name: 'Bay Scallops', search_hint: 'bay scallops', is_branded: false },
      { name: 'Lobster Tails', search_hint: 'frozen lobster tails', is_branded: false },
      { name: 'Crab Legs', search_hint: 'snow crab legs', is_branded: false },
      { name: 'Clams (littleneck)', search_hint: 'littleneck clams', is_branded: false },
      { name: 'Oysters', search_hint: 'fresh oysters', is_branded: false },
      { name: 'Imitation Crab', search_hint: 'imitation crab meat', is_branded: false },
      { name: 'Smoked Salmon', search_hint: 'smoked salmon lox', is_branded: false },
      { name: 'Fish Sticks (frozen)', search_hint: 'frozen fish sticks', is_branded: false },
      { name: "Gorton's Fish", search_hint: "Gorton's fish fillets frozen", is_branded: true },
    ],
  },

  // ── DELI & PREPARED ───────────────────────────────────────────────────
  {
    key: 'deli',
    label: 'Deli & Prepared Foods',
    emoji: '🥪',
    items: [
      { name: 'Rotisserie Chicken', search_hint: 'rotisserie chicken whole', is_branded: false },
      { name: 'Sliced Turkey Breast', search_hint: 'deli sliced turkey breast', is_branded: false },
      { name: 'Sliced Ham', search_hint: 'deli sliced honey ham', is_branded: false },
      { name: 'Sliced Roast Beef', search_hint: 'deli sliced roast beef', is_branded: false },
      { name: 'Pepperoni', search_hint: 'pepperoni sliced', is_branded: false },
      { name: 'Salami', search_hint: 'salami sliced', is_branded: false },
      { name: 'Hummus', search_hint: 'hummus classic', is_branded: false },
      { name: 'Guacamole', search_hint: 'guacamole fresh', is_branded: false },
      { name: 'Fresh Salsa', search_hint: 'fresh salsa deli', is_branded: false },
      { name: 'Macaroni Salad', search_hint: 'deli macaroni salad', is_branded: false },
      { name: 'Potato Salad', search_hint: 'deli potato salad', is_branded: false },
      { name: 'Coleslaw', search_hint: 'deli coleslaw', is_branded: false },
      { name: 'Spring Rolls (prepared)', search_hint: 'prepared spring rolls', is_branded: false },
      { name: 'Sabra Hummus', search_hint: 'Sabra hummus classic', is_branded: true },
      { name: "Boar's Head Turkey", search_hint: "Boar's Head turkey breast", is_branded: true },
    ],
  },

  // ── FROZEN FOODS ─────────────────────────────────────────────────────
  {
    key: 'frozen',
    label: 'Frozen Foods',
    emoji: '🧊',
    items: [
      { name: 'Frozen Pizza', search_hint: 'frozen pizza', is_branded: false },
      { name: 'Frozen Chicken Nuggets', search_hint: 'frozen chicken nuggets', is_branded: false },
      { name: 'Frozen Chicken Strips', search_hint: 'frozen chicken tenders strips', is_branded: false },
      { name: 'Frozen French Fries', search_hint: 'frozen french fries', is_branded: false },
      { name: 'Frozen Tater Tots', search_hint: 'frozen tater tots', is_branded: false },
      { name: 'Frozen Onion Rings', search_hint: 'frozen onion rings', is_branded: false },
      { name: 'Frozen Mixed Vegetables', search_hint: 'frozen mixed vegetables bag', is_branded: false },
      { name: 'Frozen Broccoli', search_hint: 'frozen broccoli florets', is_branded: false },
      { name: 'Frozen Corn', search_hint: 'frozen sweet corn', is_branded: false },
      { name: 'Frozen Peas', search_hint: 'frozen peas', is_branded: false },
      { name: 'Frozen Green Beans', search_hint: 'frozen green beans', is_branded: false },
      { name: 'Frozen Edamame', search_hint: 'frozen shelled edamame', is_branded: false },
      { name: 'Frozen Waffles', search_hint: 'frozen waffles', is_branded: false },
      { name: 'Frozen Pancakes', search_hint: 'frozen pancakes', is_branded: false },
      { name: 'Frozen Burritos', search_hint: 'frozen burritos', is_branded: false },
      { name: 'Frozen Breakfast Sandwiches', search_hint: 'frozen breakfast sandwiches', is_branded: false },
      { name: 'Frozen Fish Sticks', search_hint: 'frozen fish sticks', is_branded: false },
      { name: 'Frozen Shrimp', search_hint: 'frozen cooked shrimp', is_branded: false },
      { name: 'Frozen Mac & Cheese', search_hint: 'frozen mac and cheese', is_branded: false },
      { name: 'Frozen Lasagna', search_hint: 'frozen lasagna', is_branded: false },
      { name: 'Frozen Pot Pie', search_hint: 'frozen chicken pot pie', is_branded: false },
      { name: 'DiGiorno Pizza', search_hint: 'DiGiorno frozen pizza rising crust', is_branded: true },
      { name: 'Totino\'s Pizza Rolls', search_hint: "Totino's pizza rolls", is_branded: true },
      { name: 'Eggo Waffles', search_hint: 'Eggo frozen waffles', is_branded: true },
      { name: 'Jimmy Dean Breakfast', search_hint: 'Jimmy Dean frozen breakfast sandwich', is_branded: true },
      { name: 'Amy\'s Frozen Meals', search_hint: "Amy's organic frozen meals", is_branded: true },
      { name: 'Lean Cuisine Meal', search_hint: 'Lean Cuisine frozen entree', is_branded: true },
      { name: "Stouffer's Meal", search_hint: "Stouffer's frozen entree", is_branded: true },
      { name: 'Bird\'s Eye Vegetables', search_hint: "Bird's Eye frozen vegetables", is_branded: true },
      { name: 'Green Giant Vegetables', search_hint: 'Green Giant frozen vegetables', is_branded: true },
    ],
  },

  // ── CEREAL & BREAKFAST ────────────────────────────────────────────────
  {
    key: 'cereal',
    label: 'Cereal & Breakfast',
    emoji: '🥣',
    items: [
      { name: 'Cheerios', search_hint: 'Cheerios cereal original', is_branded: true },
      { name: 'Honey Nut Cheerios', search_hint: 'Honey Nut Cheerios', is_branded: true },
      { name: 'Frosted Flakes', search_hint: "Kellogg's Frosted Flakes", is_branded: true },
      { name: 'Frosted Mini-Wheats', search_hint: "Kellogg's Frosted Mini-Wheats", is_branded: true },
      { name: 'Raisin Bran', search_hint: "Kellogg's Raisin Bran", is_branded: true },
      { name: 'Froot Loops', search_hint: "Kellogg's Froot Loops", is_branded: true },
      { name: 'Honey Bunches of Oats', search_hint: 'Honey Bunches of Oats cereal', is_branded: true },
      { name: 'Cocoa Puffs', search_hint: 'Cocoa Puffs cereal', is_branded: true },
      { name: 'Lucky Charms', search_hint: 'Lucky Charms cereal', is_branded: true },
      { name: 'Cinnamon Toast Crunch', search_hint: 'Cinnamon Toast Crunch cereal', is_branded: true },
      { name: 'Rice Krispies', search_hint: "Kellogg's Rice Krispies", is_branded: true },
      { name: 'Special K', search_hint: "Kellogg's Special K", is_branded: true },
      { name: 'Life Cereal', search_hint: 'Quaker Life cereal', is_branded: true },
      { name: 'Cap\'n Crunch', search_hint: "Cap'n Crunch cereal", is_branded: true },
      { name: 'Grape Nuts', search_hint: 'Post Grape-Nuts cereal', is_branded: true },
      { name: 'Quaker Old Fashioned Oats', search_hint: 'Quaker old fashioned oats 42 oz', is_branded: true },
      { name: 'Quick Oats', search_hint: 'quick oats', is_branded: false },
      { name: 'Instant Oatmeal Packets', search_hint: 'Quaker instant oatmeal variety pack', is_branded: true },
      { name: 'Granola', search_hint: 'granola', is_branded: false },
      { name: 'Pancake Mix', search_hint: 'Bisquick pancake mix', is_branded: true },
      { name: 'Aunt Jemima Pancake Mix', search_hint: 'Pearl Milling pancake mix', is_branded: true },
      { name: 'Maple Syrup', search_hint: 'pure maple syrup', is_branded: false },
      { name: 'Pop-Tarts', search_hint: "Kellogg's Pop-Tarts", is_branded: true },
      { name: 'Nutri-Grain Bars', search_hint: "Kellogg's Nutri-Grain bars", is_branded: true },
      { name: 'Nature Valley Granola Bars', search_hint: 'Nature Valley granola bars', is_branded: true },
    ],
  },

  // ── SNACKS & CHIPS ───────────────────────────────────────────────────
  {
    key: 'snacks',
    label: 'Snacks & Chips',
    emoji: '🍿',
    items: [
      { name: "Lay's Classic Chips", search_hint: "Lay's Classic potato chips", is_branded: true },
      { name: "Lay's Wavy", search_hint: "Lay's Wavy potato chips", is_branded: true },
      { name: "Lay's Barbecue", search_hint: "Lay's Barbecue chips", is_branded: true },
      { name: 'Doritos Nacho Cheese', search_hint: 'Doritos Nacho Cheese', is_branded: true },
      { name: 'Doritos Cool Ranch', search_hint: 'Doritos Cool Ranch', is_branded: true },
      { name: 'Tostitos Chips', search_hint: 'Tostitos tortilla chips', is_branded: true },
      { name: 'Fritos', search_hint: 'Fritos corn chips original', is_branded: true },
      { name: 'Cheetos', search_hint: 'Cheetos crunchy', is_branded: true },
      { name: 'Pringles Original', search_hint: 'Pringles original', is_branded: true },
      { name: 'Pringles Sour Cream', search_hint: 'Pringles sour cream and onion', is_branded: true },
      { name: 'Cheez-Its', search_hint: 'Cheez-It crackers original', is_branded: true },
      { name: 'Goldfish Crackers', search_hint: 'Pepperidge Farm Goldfish crackers', is_branded: true },
      { name: 'Ritz Crackers', search_hint: 'Ritz crackers', is_branded: true },
      { name: 'Triscuits', search_hint: 'Triscuit crackers original', is_branded: true },
      { name: 'Wheat Thins', search_hint: 'Wheat Thins crackers', is_branded: true },
      { name: 'Club Crackers', search_hint: 'Club crackers', is_branded: true },
      { name: 'Microwave Popcorn', search_hint: 'microwave popcorn butter', is_branded: false },
      { name: 'Orville Redenbacher Popcorn', search_hint: 'Orville Redenbacher microwave popcorn', is_branded: true },
      { name: 'SkinnyPop Popcorn', search_hint: 'SkinnyPop popcorn', is_branded: true },
      { name: 'Pretzels', search_hint: 'Snyder\'s pretzels', is_branded: true },
      { name: 'Rold Gold Pretzels', search_hint: 'Rold Gold pretzels', is_branded: true },
      { name: 'Trail Mix', search_hint: 'trail mix variety', is_branded: false },
      { name: 'Mixed Nuts', search_hint: 'mixed nuts salted', is_branded: false },
      { name: 'Almonds', search_hint: 'dry roasted almonds', is_branded: false },
      { name: 'Cashews', search_hint: 'cashews salted', is_branded: false },
      { name: 'Peanuts', search_hint: 'dry roasted peanuts', is_branded: false },
      { name: 'Sunflower Seeds', search_hint: 'sunflower seeds', is_branded: false },
      { name: 'Pistachios', search_hint: 'pistachios roasted salted', is_branded: false },
      { name: 'Rice Cakes', search_hint: 'rice cakes lightly salted', is_branded: false },
      { name: 'Fruit Snacks', search_hint: 'Welch\'s fruit snacks', is_branded: true },
      { name: 'Beef Jerky', search_hint: 'beef jerky original', is_branded: false },
      { name: 'Jack Link\'s Jerky', search_hint: "Jack Link's beef jerky", is_branded: true },
      { name: 'Veggie Straws', search_hint: 'Sensible Portions veggie straws', is_branded: true },
      { name: 'Granola Bars', search_hint: 'chewy granola bars', is_branded: false },
      { name: 'Clif Bar', search_hint: 'Clif Bar energy bar', is_branded: true },
      { name: 'KIND Bar', search_hint: 'KIND bars variety', is_branded: true },
      { name: 'Lara Bar', search_hint: 'Larabar fruit nut bars', is_branded: true },
    ],
  },

  // ── COOKIES & SWEETS ─────────────────────────────────────────────────
  {
    key: 'cookies',
    label: 'Cookies & Sweets',
    emoji: '🍪',
    items: [
      { name: 'Oreos', search_hint: 'Oreo cookies', is_branded: true },
      { name: 'Oreo Double Stuf', search_hint: 'Oreo Double Stuf cookies', is_branded: true },
      { name: 'Chips Ahoy!', search_hint: 'Chips Ahoy chocolate chip cookies', is_branded: true },
      { name: 'Chips Ahoy! Chewy', search_hint: 'Chips Ahoy chewy cookies', is_branded: true },
      { name: 'Nutter Butter', search_hint: 'Nutter Butter peanut butter cookies', is_branded: true },
      { name: 'Milano Cookies', search_hint: 'Pepperidge Farm Milano cookies', is_branded: true },
      { name: 'Keebler Fudge Stripes', search_hint: 'Keebler Fudge Stripes cookies', is_branded: true },
      { name: 'Famous Amos Cookies', search_hint: 'Famous Amos chocolate chip cookies', is_branded: true },
      { name: 'Lofthouse Sugar Cookies', search_hint: 'Lofthouse frosted sugar cookies', is_branded: true },
      { name: 'Brownie Mix', search_hint: 'Betty Crocker brownie mix', is_branded: true },
      { name: 'Duncan Hines Cake Mix', search_hint: 'Duncan Hines cake mix', is_branded: true },
      { name: 'Betty Crocker Cake Mix', search_hint: 'Betty Crocker cake mix', is_branded: true },
      { name: 'Betty Crocker Frosting', search_hint: 'Betty Crocker frosting', is_branded: true },
      { name: 'Jell-O Pudding Mix', search_hint: 'Jell-O pudding mix instant', is_branded: true },
      { name: 'Jell-O Gelatin', search_hint: 'Jell-O gelatin mix', is_branded: true },
      { name: 'Vanilla Ice Cream', search_hint: 'vanilla ice cream half gallon', is_branded: false },
      { name: 'Chocolate Ice Cream', search_hint: 'chocolate ice cream half gallon', is_branded: false },
      { name: 'Breyers Ice Cream', search_hint: 'Breyers ice cream natural vanilla', is_branded: true },
      { name: 'Häagen-Dazs Ice Cream', search_hint: 'Haagen-Dazs ice cream vanilla', is_branded: true },
      { name: "Ben & Jerry's", search_hint: "Ben and Jerry's ice cream pint", is_branded: true },
      { name: 'Talenti Gelato', search_hint: 'Talenti gelato pint', is_branded: true },
      { name: 'Popsicles', search_hint: 'Popsicle ice pops', is_branded: true },
      { name: 'Fudge Bars', search_hint: 'fudge bars frozen', is_branded: false },
      { name: 'Klondike Bars', search_hint: 'Klondike ice cream bars', is_branded: true },
      { name: 'Twinkies', search_hint: 'Hostess Twinkies', is_branded: true },
      { name: 'Little Debbie Cakes', search_hint: 'Little Debbie snack cakes', is_branded: true },
    ],
  },

  // ── CANDY ─────────────────────────────────────────────────────────────
  {
    key: 'candy',
    label: 'Candy & Chocolate',
    emoji: '🍬',
    items: [
      { name: 'M&Ms', search_hint: 'M&Ms chocolate candy', is_branded: true },
      { name: 'Snickers', search_hint: 'Snickers candy bars', is_branded: true },
      { name: 'Reese\'s Peanut Butter Cups', search_hint: "Reese's Peanut Butter Cups", is_branded: true },
      { name: 'Kit Kat', search_hint: 'Kit Kat chocolate wafer bars', is_branded: true },
      { name: 'Twix', search_hint: 'Twix candy bars', is_branded: true },
      { name: 'Milky Way', search_hint: 'Milky Way candy bars', is_branded: true },
      { name: '3 Musketeers', search_hint: '3 Musketeers candy bars', is_branded: true },
      { name: 'Butterfinger', search_hint: 'Butterfinger candy bars', is_branded: true },
      { name: 'Nerds', search_hint: 'Nerds candy', is_branded: true },
      { name: 'Sour Patch Kids', search_hint: 'Sour Patch Kids candy', is_branded: true },
      { name: 'Skittles', search_hint: 'Skittles original candy', is_branded: true },
      { name: 'Starburst', search_hint: 'Starburst original fruit chews', is_branded: true },
      { name: 'Swedish Fish', search_hint: 'Swedish Fish candy', is_branded: true },
      { name: 'Haribo Gummy Bears', search_hint: 'Haribo Gold-Bears gummy candy', is_branded: true },
      { name: 'Twizzlers', search_hint: 'Twizzlers strawberry licorice', is_branded: true },
      { name: 'Jolly Ranchers', search_hint: 'Jolly Rancher hard candy', is_branded: true },
      { name: 'Hershey\'s Chocolate Bar', search_hint: "Hershey's milk chocolate bar", is_branded: true },
      { name: 'Dove Chocolate', search_hint: 'Dove milk chocolate promises', is_branded: true },
      { name: 'Lindt Chocolate', search_hint: 'Lindt Excellence dark chocolate bar', is_branded: true },
      { name: 'Ghirardelli Chocolate', search_hint: 'Ghirardelli chocolate squares', is_branded: true },
      { name: 'York Peppermint Patties', search_hint: 'York Peppermint Patties', is_branded: true },
      { name: 'Chewing Gum', search_hint: 'Extra spearmint gum', is_branded: true },
    ],
  },

  // ── BEVERAGES ────────────────────────────────────────────────────────
  {
    key: 'beverages',
    label: 'Beverages',
    emoji: '🥤',
    items: [
      { name: 'Coca-Cola (12 pk cans)', search_hint: 'Coca-Cola 12 pack cans', is_branded: true },
      { name: 'Pepsi (12 pk cans)', search_hint: 'Pepsi 12 pack cans', is_branded: true },
      { name: 'Sprite (12 pk)', search_hint: 'Sprite 12 pack cans', is_branded: true },
      { name: 'Dr Pepper (12 pk)', search_hint: 'Dr Pepper 12 pack cans', is_branded: true },
      { name: 'Mountain Dew (12 pk)', search_hint: 'Mountain Dew 12 pack cans', is_branded: true },
      { name: '7UP (12 pk)', search_hint: '7UP 12 pack cans', is_branded: true },
      { name: 'Ginger Ale', search_hint: "Canada Dry ginger ale", is_branded: true },
      { name: 'Root Beer', search_hint: "A&W root beer 12 pack", is_branded: true },
      { name: 'Gatorade (variety)', search_hint: 'Gatorade sports drink variety pack', is_branded: true },
      { name: 'Powerade', search_hint: 'Powerade sports drink', is_branded: true },
      { name: 'Propel Water', search_hint: 'Propel flavored water', is_branded: true },
      { name: 'Vitamin Water', search_hint: 'vitaminwater variety', is_branded: true },
      { name: 'Monster Energy', search_hint: 'Monster Energy drink', is_branded: true },
      { name: 'Red Bull', search_hint: 'Red Bull energy drink', is_branded: true },
      { name: 'Orange Juice (52 oz)', search_hint: 'orange juice 52 oz carton', is_branded: false },
      { name: 'Tropicana OJ', search_hint: 'Tropicana Pure Premium orange juice', is_branded: true },
      { name: 'Simply Orange Juice', search_hint: 'Simply Orange juice', is_branded: true },
      { name: 'Apple Juice', search_hint: 'apple juice 64 oz', is_branded: false },
      { name: 'Grape Juice', search_hint: "Welch's grape juice", is_branded: true },
      { name: 'Bottled Water (24 pk)', search_hint: 'water bottles 24 pack 16.9 oz', is_branded: false },
      { name: 'Dasani Water', search_hint: 'Dasani water bottles', is_branded: true },
      { name: 'Aquafina Water', search_hint: 'Aquafina water bottles', is_branded: true },
      { name: 'LaCroix Sparkling Water', search_hint: 'LaCroix sparkling water 12 pack', is_branded: true },
      { name: 'Bubly Sparkling Water', search_hint: 'bubly sparkling water 12 pack', is_branded: true },
      { name: 'Sparkling Ice', search_hint: 'Sparkling Ice flavored water', is_branded: true },
      { name: 'Ground Coffee', search_hint: 'ground coffee medium roast', is_branded: false },
      { name: 'Folgers Coffee', search_hint: 'Folgers Classic Roast ground coffee', is_branded: true },
      { name: 'Maxwell House Coffee', search_hint: 'Maxwell House ground coffee', is_branded: true },
      { name: 'Starbucks Ground Coffee', search_hint: 'Starbucks Pike Place ground coffee', is_branded: true },
      { name: 'Dunkin\' Ground Coffee', search_hint: "Dunkin' original blend ground coffee", is_branded: true },
      { name: 'K-Cups (variety)', search_hint: 'K-Cup coffee pods variety pack', is_branded: false },
      { name: 'Lipton Tea Bags', search_hint: 'Lipton tea bags 100 ct', is_branded: true },
      { name: 'Bigelow Tea', search_hint: 'Bigelow green tea bags', is_branded: true },
      { name: 'Snapple', search_hint: 'Snapple iced tea', is_branded: true },
      { name: 'Gold Peak Iced Tea', search_hint: 'Gold Peak sweet tea', is_branded: true },
      { name: 'Arizona Iced Tea', search_hint: 'Arizona iced tea', is_branded: true },
      { name: 'Liquid IV', search_hint: 'Liquid IV hydration multiplier', is_branded: true },
    ],
  },

  // ── CANNED & PANTRY ──────────────────────────────────────────────────
  {
    key: 'canned',
    label: 'Canned & Pantry',
    emoji: '🥫',
    items: [
      { name: 'Diced Tomatoes', search_hint: 'diced tomatoes canned 14.5 oz', is_branded: false },
      { name: 'Crushed Tomatoes', search_hint: 'crushed tomatoes canned 28 oz', is_branded: false },
      { name: 'Tomato Sauce', search_hint: 'tomato sauce canned 8 oz', is_branded: false },
      { name: 'Tomato Paste', search_hint: 'tomato paste canned 6 oz', is_branded: false },
      { name: 'Chicken Broth (32 oz)', search_hint: 'chicken broth 32 oz carton', is_branded: false },
      { name: 'Beef Broth', search_hint: 'beef broth 32 oz', is_branded: false },
      { name: 'Vegetable Broth', search_hint: 'vegetable broth 32 oz', is_branded: false },
      { name: 'Chicken Noodle Soup', search_hint: "Campbell's chicken noodle soup can", is_branded: true },
      { name: 'Tomato Soup', search_hint: "Campbell's condensed tomato soup", is_branded: true },
      { name: 'Progresso Soup', search_hint: 'Progresso soup', is_branded: true },
      { name: 'Black Beans', search_hint: 'black beans canned 15 oz', is_branded: false },
      { name: 'Kidney Beans', search_hint: 'kidney beans canned 15 oz', is_branded: false },
      { name: 'Chickpeas', search_hint: 'chickpeas garbanzo beans canned', is_branded: false },
      { name: 'Pinto Beans', search_hint: 'pinto beans canned', is_branded: false },
      { name: 'Refried Beans', search_hint: 'refried beans canned', is_branded: false },
      { name: 'Canned Corn', search_hint: 'whole kernel corn canned 15 oz', is_branded: false },
      { name: 'Canned Green Beans', search_hint: 'green beans canned cut', is_branded: false },
      { name: 'Canned Peas', search_hint: 'sweet peas canned', is_branded: false },
      { name: 'Canned Tuna (in water)', search_hint: 'tuna in water canned 5 oz', is_branded: false },
      { name: 'StarKist Tuna', search_hint: 'StarKist chunk light tuna in water', is_branded: true },
      { name: 'Canned Salmon', search_hint: 'pink salmon canned', is_branded: false },
      { name: 'Canned Chicken', search_hint: 'canned chicken breast', is_branded: false },
      { name: 'Sardines', search_hint: 'sardines in olive oil', is_branded: false },
      { name: 'Peanut Butter (creamy)', search_hint: 'creamy peanut butter 16 oz', is_branded: false },
      { name: 'Jif Peanut Butter', search_hint: 'Jif creamy peanut butter', is_branded: true },
      { name: 'Skippy Peanut Butter', search_hint: 'Skippy creamy peanut butter', is_branded: true },
      { name: 'Almond Butter', search_hint: 'almond butter', is_branded: false },
      { name: 'Strawberry Jam', search_hint: "Smucker's strawberry jam", is_branded: true },
      { name: 'Grape Jelly', search_hint: "Smucker's grape jelly", is_branded: true },
      { name: 'Honey', search_hint: 'pure clover honey', is_branded: false },
      { name: "Hunt's Tomatoes", search_hint: "Hunt's diced tomatoes", is_branded: true },
      { name: "Del Monte Vegetables", search_hint: 'Del Monte canned vegetables', is_branded: true },
      { name: "Rotel Diced Tomatoes", search_hint: 'Rotel original diced tomatoes chiles', is_branded: true },
    ],
  },

  // ── PASTA, RICE & GRAINS ─────────────────────────────────────────────
  {
    key: 'pasta_rice',
    label: 'Pasta, Rice & Grains',
    emoji: '🍝',
    items: [
      { name: 'Spaghetti', search_hint: 'spaghetti pasta 16 oz', is_branded: false },
      { name: 'Penne Pasta', search_hint: 'penne rigate pasta', is_branded: false },
      { name: 'Rotini Pasta', search_hint: 'rotini pasta 16 oz', is_branded: false },
      { name: 'Elbow Macaroni', search_hint: 'elbow macaroni pasta', is_branded: false },
      { name: 'Fettuccine', search_hint: 'fettuccine pasta', is_branded: false },
      { name: 'Bow Tie (Farfalle)', search_hint: 'farfalle bow tie pasta', is_branded: false },
      { name: 'Lasagna Noodles', search_hint: 'lasagna noodles', is_branded: false },
      { name: 'Angel Hair Pasta', search_hint: 'angel hair pasta', is_branded: false },
      { name: 'Gluten-Free Pasta', search_hint: 'gluten free pasta', is_branded: false },
      { name: 'Barilla Pasta', search_hint: 'Barilla pasta', is_branded: true },
      { name: 'Ronzoni Pasta', search_hint: 'Ronzoni pasta', is_branded: true },
      { name: 'Prego Pasta Sauce', search_hint: 'Prego traditional pasta sauce 24 oz', is_branded: true },
      { name: 'Ragu Pasta Sauce', search_hint: 'Ragu old world style pasta sauce', is_branded: true },
      { name: "Rao's Marinara Sauce", search_hint: "Rao's Homemade marinara sauce", is_branded: true },
      { name: 'Kraft Mac & Cheese', search_hint: 'Kraft macaroni and cheese box', is_branded: true },
      { name: "Annie's Mac & Cheese", search_hint: "Annie's macaroni and cheese", is_branded: true },
      { name: 'White Rice (5 lb)', search_hint: 'long grain white rice 5 lb', is_branded: false },
      { name: 'Brown Rice', search_hint: 'long grain brown rice', is_branded: false },
      { name: 'Jasmine Rice', search_hint: 'jasmine rice', is_branded: false },
      { name: 'Basmati Rice', search_hint: 'basmati rice', is_branded: false },
      { name: 'Rice-A-Roni', search_hint: 'Rice-A-Roni rice pilaf', is_branded: true },
      { name: 'Uncle Ben\'s Rice', search_hint: "Ben's Original ready rice", is_branded: true },
      { name: 'Quinoa', search_hint: 'quinoa', is_branded: false },
      { name: 'Lentils (dry)', search_hint: 'dry lentils green', is_branded: false },
      { name: 'Oatmeal (steel cut)', search_hint: 'steel cut oats', is_branded: false },
      { name: 'Grits', search_hint: 'grits quick cooking', is_branded: false },
      { name: 'Cornmeal', search_hint: 'yellow cornmeal', is_branded: false },
    ],
  },

  // ── BAKING ────────────────────────────────────────────────────────────
  {
    key: 'baking',
    label: 'Baking & Cooking',
    emoji: '🎂',
    items: [
      { name: 'All-Purpose Flour', search_hint: 'all purpose flour 5 lb', is_branded: false },
      { name: 'Bread Flour', search_hint: 'bread flour', is_branded: false },
      { name: 'Whole Wheat Flour', search_hint: 'whole wheat flour', is_branded: false },
      { name: 'White Granulated Sugar', search_hint: 'granulated white sugar 4 lb', is_branded: false },
      { name: 'Brown Sugar', search_hint: 'light brown sugar', is_branded: false },
      { name: 'Powdered Sugar', search_hint: 'powdered confectioners sugar', is_branded: false },
      { name: 'Baking Soda', search_hint: 'baking soda box', is_branded: false },
      { name: 'Baking Powder', search_hint: 'baking powder', is_branded: false },
      { name: 'Vanilla Extract', search_hint: 'pure vanilla extract', is_branded: false },
      { name: 'Chocolate Chips', search_hint: 'semi-sweet chocolate chips', is_branded: false },
      { name: 'Nestle Toll House Chips', search_hint: 'Nestle Toll House chocolate chips', is_branded: true },
      { name: 'Cocoa Powder', search_hint: 'unsweetened cocoa powder', is_branded: false },
      { name: 'Vegetable Shortening', search_hint: 'Crisco vegetable shortening', is_branded: true },
      { name: 'Active Dry Yeast', search_hint: 'Fleischmann\'s active dry yeast', is_branded: true },
      { name: 'Evaporated Milk', search_hint: 'evaporated milk canned', is_branded: false },
      { name: 'Sweetened Condensed Milk', search_hint: 'sweetened condensed milk', is_branded: false },
      { name: 'Pie Crust (refrigerated)', search_hint: 'Pillsbury refrigerated pie crust', is_branded: true },
      { name: 'Bread Crumbs', search_hint: 'Italian breadcrumbs', is_branded: false },
      { name: 'Panko Bread Crumbs', search_hint: 'panko breadcrumbs', is_branded: false },
      { name: 'Cornstarch', search_hint: 'cornstarch', is_branded: false },
      { name: 'Molasses', search_hint: 'molasses', is_branded: false },
      { name: 'Food Coloring', search_hint: 'food coloring set', is_branded: false },
      { name: 'Sprinkles', search_hint: 'rainbow sprinkles', is_branded: false },
      { name: 'Cream of Tartar', search_hint: 'cream of tartar', is_branded: false },
    ],
  },

  // ── CONDIMENTS & SAUCES ──────────────────────────────────────────────
  {
    key: 'condiments',
    label: 'Condiments & Sauces',
    emoji: '🧂',
    items: [
      { name: 'Ketchup', search_hint: 'ketchup 32 oz', is_branded: false },
      { name: 'Heinz Ketchup', search_hint: 'Heinz tomato ketchup 32 oz', is_branded: true },
      { name: 'Yellow Mustard', search_hint: 'yellow mustard', is_branded: false },
      { name: 'Grey Poupon Dijon', search_hint: 'Grey Poupon Dijon mustard', is_branded: true },
      { name: 'Mayonnaise', search_hint: 'mayonnaise 30 oz', is_branded: false },
      { name: "Hellmann's Mayonnaise", search_hint: "Hellmann's real mayonnaise", is_branded: true },
      { name: 'Duke\'s Mayonnaise', search_hint: "Duke's mayonnaise", is_branded: true },
      { name: 'Ranch Dressing', search_hint: 'Hidden Valley Ranch dressing', is_branded: true },
      { name: 'Italian Dressing', search_hint: 'Italian dressing', is_branded: false },
      { name: 'Caesar Dressing', search_hint: 'Caesar salad dressing', is_branded: false },
      { name: 'Balsamic Vinaigrette', search_hint: 'balsamic vinaigrette dressing', is_branded: false },
      { name: 'Thousand Island Dressing', search_hint: 'Thousand Island dressing', is_branded: false },
      { name: 'Barbecue Sauce', search_hint: 'barbecue sauce', is_branded: false },
      { name: "Sweet Baby Ray's BBQ", search_hint: "Sweet Baby Ray's barbecue sauce", is_branded: true },
      { name: 'Worcestershire Sauce', search_hint: 'Lea & Perrins Worcestershire sauce', is_branded: true },
      { name: 'Hot Sauce', search_hint: "Frank's RedHot original hot sauce", is_branded: true },
      { name: 'Tabasco', search_hint: 'Tabasco original hot sauce', is_branded: true },
      { name: 'Sriracha', search_hint: 'Huy Fong sriracha hot sauce', is_branded: true },
      { name: 'Soy Sauce', search_hint: 'soy sauce 10 oz', is_branded: false },
      { name: "Kikkoman Soy Sauce", search_hint: 'Kikkoman soy sauce', is_branded: true },
      { name: 'Teriyaki Sauce', search_hint: 'teriyaki sauce', is_branded: false },
      { name: 'Steak Sauce', search_hint: 'A1 steak sauce', is_branded: true },
      { name: 'Salsa (jar)', search_hint: 'salsa jar medium', is_branded: false },
      { name: 'Tostitos Salsa', search_hint: 'Tostitos salsa con queso', is_branded: true },
      { name: 'Pickle Relish', search_hint: 'sweet pickle relish', is_branded: false },
      { name: 'Pickles', search_hint: 'dill pickles jar', is_branded: false },
      { name: 'Vlasic Pickles', search_hint: 'Vlasic dill pickles', is_branded: true },
    ],
  },

  // ── SPICES & SEASONINGS ──────────────────────────────────────────────
  {
    key: 'spices',
    label: 'Spices & Seasonings',
    emoji: '🌿',
    items: [
      { name: 'Iodized Salt', search_hint: 'Morton iodized salt', is_branded: true },
      { name: 'Sea Salt', search_hint: 'sea salt fine', is_branded: false },
      { name: 'Black Pepper (ground)', search_hint: 'ground black pepper', is_branded: false },
      { name: 'Garlic Powder', search_hint: 'garlic powder', is_branded: false },
      { name: 'Onion Powder', search_hint: 'onion powder', is_branded: false },
      { name: 'Paprika', search_hint: 'paprika', is_branded: false },
      { name: 'Cayenne Pepper', search_hint: 'cayenne pepper', is_branded: false },
      { name: 'Chili Powder', search_hint: 'chili powder', is_branded: false },
      { name: 'Cumin', search_hint: 'ground cumin', is_branded: false },
      { name: 'Cinnamon (ground)', search_hint: 'ground cinnamon', is_branded: false },
      { name: 'Oregano', search_hint: 'dried oregano', is_branded: false },
      { name: 'Basil (dried)', search_hint: 'dried basil', is_branded: false },
      { name: 'Thyme', search_hint: 'dried thyme', is_branded: false },
      { name: 'Rosemary', search_hint: 'dried rosemary', is_branded: false },
      { name: 'Italian Seasoning', search_hint: 'Italian seasoning blend', is_branded: false },
      { name: 'Taco Seasoning', search_hint: 'Old El Paso taco seasoning', is_branded: true },
      { name: 'Ranch Seasoning Mix', search_hint: 'Hidden Valley ranch seasoning mix', is_branded: true },
      { name: 'Lemon Pepper Seasoning', search_hint: 'lemon pepper seasoning', is_branded: false },
      { name: 'Cajun Seasoning', search_hint: 'Cajun seasoning blend', is_branded: false },
      { name: 'Everything Bagel Seasoning', search_hint: 'everything bagel seasoning', is_branded: false },
      { name: 'Adobo Seasoning', search_hint: 'Goya Adobo seasoning', is_branded: true },
      { name: 'Old Bay Seasoning', search_hint: 'Old Bay seasoning', is_branded: true },
      { name: 'McCormick Spices', search_hint: 'McCormick spices variety', is_branded: true },
    ],
  },

  // ── OILS & VINEGARS ──────────────────────────────────────────────────
  {
    key: 'oils',
    label: 'Oils, Vinegars & Cooking',
    emoji: '🫒',
    items: [
      { name: 'Extra Virgin Olive Oil', search_hint: 'extra virgin olive oil', is_branded: false },
      { name: 'Vegetable Oil', search_hint: 'vegetable oil 48 oz', is_branded: false },
      { name: 'Canola Oil', search_hint: 'canola oil', is_branded: false },
      { name: 'Coconut Oil', search_hint: 'coconut oil refined', is_branded: false },
      { name: 'Sesame Oil', search_hint: 'toasted sesame oil', is_branded: false },
      { name: 'Avocado Oil', search_hint: 'avocado oil', is_branded: false },
      { name: 'Cooking Spray (Pam)', search_hint: 'Pam cooking spray original', is_branded: true },
      { name: 'White Vinegar', search_hint: 'distilled white vinegar', is_branded: false },
      { name: 'Apple Cider Vinegar', search_hint: 'apple cider vinegar', is_branded: false },
      { name: 'Balsamic Vinegar', search_hint: 'balsamic vinegar of Modena', is_branded: false },
      { name: 'Red Wine Vinegar', search_hint: 'red wine vinegar', is_branded: false },
      { name: 'Rice Wine Vinegar', search_hint: 'rice vinegar', is_branded: false },
      { name: 'Pompeian Olive Oil', search_hint: 'Pompeian extra virgin olive oil', is_branded: true },
      { name: 'Bertolli Olive Oil', search_hint: 'Bertolli olive oil', is_branded: true },
    ],
  },

  // ── INTERNATIONAL FOODS ──────────────────────────────────────────────
  {
    key: 'international',
    label: 'International & Ethnic Foods',
    emoji: '🌍',
    items: [
      { name: 'Taco Shells', search_hint: 'Old El Paso taco shells hard', is_branded: true },
      { name: 'Flour Tortillas (small)', search_hint: 'small flour tortillas fajita', is_branded: false },
      { name: 'Enchilada Sauce', search_hint: 'enchilada sauce red', is_branded: false },
      { name: 'Green Chiles (canned)', search_hint: 'diced green chiles canned', is_branded: false },
      { name: 'Coconut Milk (can)', search_hint: 'coconut milk canned', is_branded: false },
      { name: 'Curry Paste', search_hint: 'Thai red curry paste', is_branded: false },
      { name: 'Ramen Noodles', search_hint: 'ramen noodles chicken flavor', is_branded: false },
      { name: 'Nissin Cup Noodles', search_hint: 'Nissin Cup Noodles', is_branded: true },
      { name: 'Maruchan Ramen', search_hint: 'Maruchan ramen noodles', is_branded: true },
      { name: 'Udon Noodles', search_hint: 'udon noodles', is_branded: false },
      { name: 'Rice Noodles', search_hint: 'rice noodles pad thai', is_branded: false },
      { name: 'Lo Mein Noodles', search_hint: 'lo mein noodles', is_branded: false },
      { name: 'Goya Beans', search_hint: 'Goya black beans canned', is_branded: true },
      { name: 'Goya Adobo', search_hint: 'Goya Adobo all purpose seasoning', is_branded: true },
      { name: 'Sazon Goya', search_hint: 'Sazon Goya seasoning packets', is_branded: true },
      { name: 'Hoisin Sauce', search_hint: 'hoisin sauce', is_branded: false },
      { name: 'Fish Sauce', search_hint: 'Thai fish sauce', is_branded: false },
      { name: 'Oyster Sauce', search_hint: 'oyster sauce', is_branded: false },
      { name: 'Naan Bread', search_hint: 'naan bread', is_branded: false },
      { name: 'Salsa Verde', search_hint: 'salsa verde tomatillo', is_branded: false },
    ],
  },

  // ── PACKAGED MEALS ───────────────────────────────────────────────────
  {
    key: 'packaged_meals',
    label: 'Packaged Meals & Sides',
    emoji: '📦',
    items: [
      { name: 'Hamburger Helper', search_hint: 'Hamburger Helper cheeseburger macaroni', is_branded: true },
      { name: 'Kraft Mac & Cheese Deluxe', search_hint: 'Kraft Deluxe macaroni cheese', is_branded: true },
      { name: 'Velveeta Shells & Cheese', search_hint: 'Velveeta shells and cheese', is_branded: true },
      { name: 'Idahoan Instant Mashed', search_hint: 'Idahoan instant mashed potatoes', is_branded: true },
      { name: 'Betty Crocker Mashed', search_hint: 'Betty Crocker instant mashed potatoes', is_branded: true },
      { name: 'Stove Top Stuffing', search_hint: "Stove Top stuffing mix", is_branded: true },
      { name: 'Lipton Onion Soup Mix', search_hint: 'Lipton onion soup mix', is_branded: true },
      { name: 'Chicken & Rice (canned)', search_hint: 'canned chicken and rice', is_branded: false },
      { name: 'Manwich Sloppy Joe', search_hint: 'Manwich sloppy joe sauce', is_branded: true },
      { name: "Chef Boyardee", search_hint: 'Chef Boyardee ravioli', is_branded: true },
      { name: 'Spam', search_hint: 'Spam classic canned meat', is_branded: true },
      { name: 'Dinty Moore Beef Stew', search_hint: 'Dinty Moore beef stew', is_branded: true },
      { name: 'Hormel Chili', search_hint: 'Hormel chili no beans', is_branded: true },
      { name: 'Amy\'s Organic Soups', search_hint: "Amy's organic soup", is_branded: true },
      { name: 'Tasty Bite Indian Meals', search_hint: 'Tasty Bite Indian entrees', is_branded: true },
    ],
  },

  // ── BABY & INFANT ────────────────────────────────────────────────────
  {
    key: 'baby',
    label: 'Baby & Infant',
    emoji: '👶',
    items: [
      { name: 'Diapers (size 2)', search_hint: 'diapers size 2', is_branded: false },
      { name: 'Diapers (size 3)', search_hint: 'diapers size 3', is_branded: false },
      { name: 'Diapers (size 4)', search_hint: 'diapers size 4', is_branded: false },
      { name: 'Pampers Diapers', search_hint: 'Pampers Swaddlers diapers', is_branded: true },
      { name: "Huggies Diapers", search_hint: 'Huggies Little Snugglers diapers', is_branded: true },
      { name: 'Pull-Ups Training Pants', search_hint: 'Pull-Ups training pants', is_branded: true },
      { name: 'Baby Wipes', search_hint: 'baby wipes sensitive', is_branded: false },
      { name: "Pampers Baby Wipes", search_hint: 'Pampers Sensitive baby wipes', is_branded: true },
      { name: 'Huggies Natural Care Wipes', search_hint: 'Huggies Natural Care baby wipes', is_branded: true },
      { name: 'Baby Formula (Similac)', search_hint: 'Similac Advance baby formula', is_branded: true },
      { name: 'Baby Formula (Enfamil)', search_hint: 'Enfamil NeuroPro baby formula', is_branded: true },
      { name: 'Gerber Baby Food', search_hint: 'Gerber baby food purees', is_branded: true },
      { name: 'Baby Rice Cereal', search_hint: 'Gerber rice cereal infant', is_branded: true },
      { name: 'Baby Puffs', search_hint: 'Gerber Lil Crunchies baby snacks', is_branded: true },
      { name: 'Baby Shampoo', search_hint: "Johnson's baby shampoo", is_branded: true },
      { name: 'Baby Lotion', search_hint: "Johnson's baby lotion", is_branded: true },
      { name: 'Diaper Rash Cream', search_hint: 'Desitin diaper rash cream', is_branded: true },
    ],
  },

  // ── PET FOOD ──────────────────────────────────────────────────────────
  {
    key: 'pet',
    label: 'Pet Food & Supplies',
    emoji: '🐶',
    items: [
      { name: 'Dog Food (dry)', search_hint: 'dry dog food adult', is_branded: false },
      { name: 'Purina Dog Chow', search_hint: 'Purina Dog Chow adult', is_branded: true },
      { name: 'Pedigree Dog Food', search_hint: 'Pedigree adult dog food', is_branded: true },
      { name: 'Blue Buffalo Dog Food', search_hint: 'Blue Buffalo dog food', is_branded: true },
      { name: 'Dog Food (wet/canned)', search_hint: 'wet canned dog food', is_branded: false },
      { name: 'Dog Treats', search_hint: 'dog treats milk bone', is_branded: false },
      { name: 'Milk-Bone Dog Biscuits', search_hint: 'Milk-Bone dog biscuits', is_branded: true },
      { name: 'Cat Food (dry)', search_hint: 'dry cat food adult', is_branded: false },
      { name: "Purina Cat Chow", search_hint: 'Purina Cat Chow indoor', is_branded: true },
      { name: "Fancy Feast Cat Food", search_hint: 'Fancy Feast wet cat food', is_branded: true },
      { name: 'Meow Mix Cat Food', search_hint: 'Meow Mix cat food', is_branded: true },
      { name: 'Cat Litter', search_hint: 'clumping cat litter', is_branded: false },
      { name: 'Tidy Cats Litter', search_hint: "Purina Tidy Cats clumping litter", is_branded: true },
      { name: 'Bird Seed', search_hint: 'wild bird seed', is_branded: false },
      { name: 'Fish Food', search_hint: 'aquarium fish food flakes', is_branded: false },
    ],
  },

  // ── CLEANING & PAPER ─────────────────────────────────────────────────
  {
    key: 'cleaning',
    label: 'Cleaning & Paper Goods',
    emoji: '🧹',
    items: [
      { name: 'Paper Towels', search_hint: 'paper towels 6 roll', is_branded: false },
      { name: 'Bounty Paper Towels', search_hint: 'Bounty Select-A-Size paper towels', is_branded: true },
      { name: 'Toilet Paper', search_hint: 'toilet paper 12 roll', is_branded: false },
      { name: 'Charmin Ultra Soft', search_hint: 'Charmin Ultra Soft toilet paper', is_branded: true },
      { name: 'Angel Soft', search_hint: 'Angel Soft toilet paper', is_branded: true },
      { name: 'Tissues (Kleenex)', search_hint: 'Kleenex facial tissues box', is_branded: true },
      { name: 'Dish Soap', search_hint: 'dish soap', is_branded: false },
      { name: 'Dawn Dish Soap', search_hint: 'Dawn Ultra dish soap original', is_branded: true },
      { name: 'Palmolive Dish Soap', search_hint: 'Palmolive dish soap original', is_branded: true },
      { name: 'Dish Soap Pods (Cascade)', search_hint: 'Cascade Platinum dishwasher pods', is_branded: true },
      { name: 'Finish Dishwasher Tabs', search_hint: 'Finish Quantum dishwasher tablets', is_branded: true },
      { name: 'Laundry Detergent', search_hint: 'laundry detergent', is_branded: false },
      { name: 'Tide Pods', search_hint: 'Tide Pods 3-in-1 laundry', is_branded: true },
      { name: 'Tide Liquid Detergent', search_hint: 'Tide original liquid laundry detergent', is_branded: true },
      { name: 'Gain Detergent', search_hint: 'Gain original liquid laundry detergent', is_branded: true },
      { name: 'Arm & Hammer Detergent', search_hint: 'Arm and Hammer laundry detergent', is_branded: true },
      { name: 'Dryer Sheets (Bounce)', search_hint: 'Bounce dryer sheets', is_branded: true },
      { name: 'Downy Fabric Softener', search_hint: 'Downy fabric softener liquid', is_branded: true },
      { name: 'All-Purpose Cleaner', search_hint: 'all purpose cleaner spray', is_branded: false },
      { name: 'Mr. Clean Multi-Surface', search_hint: 'Mr. Clean multi-surface cleaner', is_branded: true },
      { name: 'Clorox Wipes', search_hint: 'Clorox disinfecting wipes', is_branded: true },
      { name: 'Lysol Spray', search_hint: 'Lysol disinfectant spray', is_branded: true },
      { name: 'Windex Glass Cleaner', search_hint: 'Windex original glass cleaner', is_branded: true },
      { name: 'Comet Cleanser', search_hint: 'Comet cleanser powder', is_branded: true },
      { name: 'Swiffer Refills', search_hint: 'Swiffer sweeper dry refills', is_branded: true },
      { name: 'Trash Bags (13 gal)', search_hint: 'trash bags 13 gallon', is_branded: false },
      { name: 'Glad Trash Bags', search_hint: 'Glad ForceFlex trash bags', is_branded: true },
      { name: 'Hefty Trash Bags', search_hint: 'Hefty Ultra Strong trash bags', is_branded: true },
      { name: 'Ziploc Gallon Bags', search_hint: 'Ziploc gallon storage bags', is_branded: true },
      { name: 'Ziploc Sandwich Bags', search_hint: 'Ziploc sandwich bags', is_branded: true },
      { name: 'Aluminum Foil', search_hint: 'Reynolds Wrap aluminum foil', is_branded: true },
      { name: 'Plastic Wrap', search_hint: 'plastic wrap cling wrap', is_branded: false },
      { name: 'Parchment Paper', search_hint: 'parchment paper baking', is_branded: false },
      { name: 'Sponges', search_hint: 'Scotch-Brite scrub sponges', is_branded: true },
      { name: 'Rubber Gloves', search_hint: 'rubber cleaning gloves', is_branded: false },
    ],
  },

  // ── PERSONAL CARE ────────────────────────────────────────────────────
  {
    key: 'personal_care',
    label: 'Personal Care',
    emoji: '🧴',
    items: [
      { name: 'Shampoo', search_hint: 'shampoo all hair types', is_branded: false },
      { name: 'Head & Shoulders', search_hint: 'Head and Shoulders Classic Clean shampoo', is_branded: true },
      { name: 'Pantene Shampoo', search_hint: 'Pantene Pro-V shampoo', is_branded: true },
      { name: 'Herbal Essences', search_hint: 'Herbal Essences shampoo', is_branded: true },
      { name: 'Dove Shampoo', search_hint: 'Dove Intensive Repair shampoo', is_branded: true },
      { name: 'Conditioner', search_hint: 'hair conditioner', is_branded: false },
      { name: 'Pantene Conditioner', search_hint: 'Pantene conditioner', is_branded: true },
      { name: 'Body Wash', search_hint: 'body wash shower gel', is_branded: false },
      { name: 'Dove Body Wash', search_hint: 'Dove Beauty body wash', is_branded: true },
      { name: 'Old Spice Body Wash', search_hint: 'Old Spice body wash men', is_branded: true },
      { name: 'Irish Spring Bar Soap', search_hint: 'Irish Spring bar soap', is_branded: true },
      { name: 'Dove Bar Soap', search_hint: 'Dove moisturizing bar soap', is_branded: true },
      { name: 'Deodorant', search_hint: 'deodorant antiperspirant', is_branded: false },
      { name: 'Old Spice Deodorant', search_hint: 'Old Spice antiperspirant deodorant', is_branded: true },
      { name: 'Dove Deodorant', search_hint: 'Dove Advanced Care deodorant', is_branded: true },
      { name: 'Secret Deodorant', search_hint: 'Secret clinical strength deodorant', is_branded: true },
      { name: 'Degree Deodorant', search_hint: 'Degree antiperspirant deodorant', is_branded: true },
      { name: 'Toothpaste', search_hint: 'toothpaste fluoride', is_branded: false },
      { name: 'Colgate Toothpaste', search_hint: 'Colgate Optic White toothpaste', is_branded: true },
      { name: 'Crest Toothpaste', search_hint: 'Crest 3D White toothpaste', is_branded: true },
      { name: 'Sensodyne Toothpaste', search_hint: 'Sensodyne sensitivity toothpaste', is_branded: true },
      { name: 'Mouthwash', search_hint: 'Listerine antiseptic mouthwash', is_branded: true },
      { name: 'Toothbrush', search_hint: 'toothbrush soft bristle', is_branded: false },
      { name: 'Oral-B Toothbrush', search_hint: 'Oral-B manual toothbrush', is_branded: true },
      { name: 'Dental Floss', search_hint: 'dental floss', is_branded: false },
      { name: 'Razor (disposable)', search_hint: 'disposable razors', is_branded: false },
      { name: 'Gillette Razors', search_hint: 'Gillette Mach3 razor', is_branded: true },
      { name: 'Venus Razors', search_hint: 'Gillette Venus razor for women', is_branded: true },
      { name: 'Shaving Cream', search_hint: 'shaving cream gel', is_branded: false },
      { name: 'Barbasol Shaving Cream', search_hint: 'Barbasol shaving cream', is_branded: true },
      { name: 'Face Wash', search_hint: 'face wash cleanser', is_branded: false },
      { name: 'CeraVe Face Wash', search_hint: 'CeraVe hydrating facial cleanser', is_branded: true },
      { name: 'Neutrogena Face Wash', search_hint: 'Neutrogena oil free acne wash', is_branded: true },
      { name: 'Moisturizer', search_hint: 'face moisturizer SPF', is_branded: false },
      { name: 'Sunscreen SPF 50', search_hint: 'sunscreen SPF 50 face body', is_branded: false },
      { name: 'Coppertone Sunscreen', search_hint: 'Coppertone Sport SPF 50 sunscreen', is_branded: true },
      { name: 'Band-Aids', search_hint: 'Band-Aid adhesive bandages variety', is_branded: true },
      { name: 'Neosporin', search_hint: 'Neosporin antibiotic ointment', is_branded: true },
      { name: 'Cotton Balls', search_hint: 'cotton balls bag', is_branded: false },
      { name: 'Q-Tips Cotton Swabs', search_hint: 'Q-Tips cotton swabs 500 ct', is_branded: true },
      { name: 'Hand Sanitizer', search_hint: 'hand sanitizer gel', is_branded: false },
      { name: 'Purell Hand Sanitizer', search_hint: 'Purell Advanced hand sanitizer', is_branded: true },
    ],
  },

  // ── HEALTH & MEDICINE ────────────────────────────────────────────────
  {
    key: 'health',
    label: 'Health & Medicine',
    emoji: '💊',
    items: [
      { name: 'Tylenol Extra Strength', search_hint: 'Tylenol Extra Strength 500mg acetaminophen', is_branded: true },
      { name: 'Advil Ibuprofen', search_hint: 'Advil ibuprofen 200mg', is_branded: true },
      { name: 'Aleve Naproxen', search_hint: 'Aleve naproxen sodium', is_branded: true },
      { name: 'Aspirin', search_hint: 'Bayer aspirin 325mg', is_branded: true },
      { name: 'Dayquil Cold & Flu', search_hint: 'Vicks DayQuil Cold Flu', is_branded: true },
      { name: 'Nyquil Night', search_hint: 'Vicks NyQuil nighttime cold flu', is_branded: true },
      { name: 'Mucinex', search_hint: 'Mucinex 12-hour extended release', is_branded: true },
      { name: 'Claritin Allergy', search_hint: 'Claritin 24-hour non-drowsy allergy', is_branded: true },
      { name: 'Zyrtec Allergy', search_hint: 'Zyrtec 24-hour allergy relief', is_branded: true },
      { name: 'Flonase Nasal Spray', search_hint: 'Flonase Sensimist allergy relief', is_branded: true },
      { name: 'Pepto-Bismol', search_hint: 'Pepto-Bismol liquid upset stomach', is_branded: true },
      { name: 'Tums Antacid', search_hint: 'Tums antacid chewable tablets', is_branded: true },
      { name: 'Rolaids', search_hint: 'Rolaids antacid tablets', is_branded: true },
      { name: 'Imodium', search_hint: 'Imodium A-D anti-diarrheal', is_branded: true },
      { name: 'Miralax', search_hint: 'MiraLAX laxative powder', is_branded: true },
      { name: 'Vitamin C 1000mg', search_hint: 'Vitamin C 1000mg supplement', is_branded: false },
      { name: 'Vitamin D3', search_hint: 'Vitamin D3 2000 IU supplement', is_branded: false },
      { name: 'Multivitamins', search_hint: 'multivitamin daily adults', is_branded: false },
      { name: 'One A Day Vitamins', search_hint: 'One A Day multivitamin', is_branded: true },
      { name: 'Centrum Vitamins', search_hint: 'Centrum adult multivitamin', is_branded: true },
      { name: 'Fish Oil Omega-3', search_hint: 'fish oil omega-3 1000mg', is_branded: false },
      { name: 'Melatonin 5mg', search_hint: 'melatonin 5mg sleep aid', is_branded: false },
      { name: 'Zinc Supplement', search_hint: 'zinc supplement 50mg', is_branded: false },
      { name: 'Thermometer', search_hint: 'digital thermometer oral', is_branded: false },
    ],
  },

  // ── BREAKFAST FOODS ──────────────────────────────────────────────────
  {
    key: 'breakfast',
    label: 'Breakfast Foods',
    emoji: '🍳',
    items: [
      { name: 'Bacon (thick cut)', search_hint: 'thick cut bacon', is_branded: false },
      { name: 'Turkey Sausage Links', search_hint: 'turkey sausage breakfast links', is_branded: false },
      { name: 'Pork Sausage Patties', search_hint: 'pork sausage patties frozen', is_branded: false },
      { name: 'Jimmy Dean Sausage Roll', search_hint: 'Jimmy Dean pork sausage roll', is_branded: true },
      { name: 'Hash Browns (frozen)', search_hint: 'frozen hash browns shredded', is_branded: false },
      { name: 'Orange Juice (small)', search_hint: 'orange juice 12 oz', is_branded: false },
      { name: 'Cream Cheese (for bagels)', search_hint: 'cream cheese bagel spread', is_branded: false },
      { name: 'Jam (strawberry)', search_hint: "Smucker's strawberry preserves", is_branded: true },
      { name: 'Peanut Butter', search_hint: 'peanut butter creamy spread', is_branded: false },
      { name: 'Nutella', search_hint: 'Nutella hazelnut spread', is_branded: true },
      { name: 'Toaster Pastries', search_hint: 'Pop-Tarts toaster pastries', is_branded: true },
      { name: 'Breakfast Bars', search_hint: 'Nutri-Grain breakfast bars', is_branded: true },
    ],
  },

  // ── YOGURT & REFRIGERATED SNACKS ─────────────────────────────────────
  {
    key: 'yogurt',
    label: 'Yogurt & Refrigerated Snacks',
    emoji: '🍦',
    items: [
      { name: 'Greek Yogurt (vanilla)', search_hint: 'vanilla Greek yogurt', is_branded: false },
      { name: 'Chobani Greek Yogurt', search_hint: 'Chobani Greek yogurt vanilla', is_branded: true },
      { name: 'Fage Greek Yogurt', search_hint: 'Fage Total 0% Greek yogurt', is_branded: true },
      { name: 'Yoplait Yogurt', search_hint: 'Yoplait original yogurt', is_branded: true },
      { name: 'Dannon Light + Fit', search_hint: 'Dannon Light and Fit Greek yogurt', is_branded: true },
      { name: 'Siggi\'s Yogurt', search_hint: "Siggi's Icelandic skyr", is_branded: true },
      { name: 'Kids Yogurt Tubes', search_hint: 'Go-Gurt yogurt tubes kids', is_branded: true },
      { name: 'Activia Probiotic', search_hint: 'Activia probiotic yogurt', is_branded: true },
      { name: 'String Cheese', search_hint: 'mozzarella string cheese', is_branded: false },
      { name: 'Babybel Cheese Snacks', search_hint: 'Mini Babybel cheese snacks', is_branded: true },
      { name: 'Hummus & Pretzels Pack', search_hint: 'Sabra hummus snack pack', is_branded: true },
      { name: 'Lunchables', search_hint: 'Lunchables lunch kit', is_branded: true },
      { name: 'Snack Pack Pudding', search_hint: 'Snack Pack pudding cups', is_branded: true },
      { name: 'Jell-O Cups', search_hint: 'Jell-O gelatin cups snack', is_branded: true },
    ],
  },

  // ── BEVERAGES (ALCOHOL) ──────────────────────────────────────────────
  {
    key: 'alcohol',
    label: 'Beer, Wine & Spirits',
    emoji: '🍺',
    items: [
      { name: 'Bud Light (12 pk)', search_hint: 'Bud Light 12 pack cans beer', is_branded: true },
      { name: 'Budweiser (12 pk)', search_hint: 'Budweiser 12 pack cans', is_branded: true },
      { name: 'Coors Light (12 pk)', search_hint: 'Coors Light 12 pack cans', is_branded: true },
      { name: 'Miller Lite (12 pk)', search_hint: 'Miller Lite 12 pack cans', is_branded: true },
      { name: 'Michelob Ultra (12 pk)', search_hint: 'Michelob Ultra 12 pack cans', is_branded: true },
      { name: 'Corona Extra (12 pk)', search_hint: 'Corona Extra 12 pack bottles', is_branded: true },
      { name: 'Modelo Especial (12 pk)', search_hint: 'Modelo Especial 12 pack cans', is_branded: true },
      { name: 'Heineken (12 pk)', search_hint: 'Heineken 12 pack bottles', is_branded: true },
      { name: 'Stella Artois (12 pk)', search_hint: 'Stella Artois 12 pack bottles', is_branded: true },
      { name: 'Blue Moon (6 pk)', search_hint: 'Blue Moon Belgian White 6 pack', is_branded: true },
      { name: 'Samuel Adams Boston Lager', search_hint: 'Samuel Adams Boston Lager', is_branded: true },
      { name: 'Seltzer (White Claw)', search_hint: 'White Claw hard seltzer variety pack', is_branded: true },
      { name: 'Seltzer (Truly)', search_hint: 'Truly hard seltzer variety pack', is_branded: true },
      { name: 'Wine (Cabernet)', search_hint: 'Cabernet Sauvignon wine bottle', is_branded: false },
      { name: 'Wine (Chardonnay)', search_hint: 'Chardonnay white wine bottle', is_branded: false },
      { name: 'Josh Cellars Wine', search_hint: 'Josh Cellars Cabernet Sauvignon', is_branded: true },
      { name: 'Kim Crawford Sauvignon Blanc', search_hint: 'Kim Crawford Sauvignon Blanc', is_branded: true },
    ],
  },
];

// ── BRANDS ─────────────────────────────────────────────────────────────────
export const BRANDS = [
  // Beverages
  { key: 'coca_cola', label: 'Coca-Cola', emoji: '🥤', search: 'Coca-Cola' },
  { key: 'pepsi', label: 'Pepsi', emoji: '🥤', search: 'Pepsi' },
  { key: 'sprite', label: 'Sprite', emoji: '🥤', search: 'Sprite' },
  { key: 'dr_pepper', label: 'Dr Pepper', emoji: '🥤', search: 'Dr Pepper' },
  { key: 'mountain_dew', label: 'Mountain Dew', emoji: '🟡', search: 'Mountain Dew' },
  { key: 'gatorade', label: 'Gatorade', emoji: '⚡', search: 'Gatorade' },
  { key: 'red_bull', label: 'Red Bull', emoji: '🐂', search: 'Red Bull' },
  { key: 'monster', label: 'Monster Energy', emoji: '🟢', search: 'Monster Energy drink' },
  { key: 'tropicana', label: 'Tropicana', emoji: '🍊', search: 'Tropicana orange juice' },
  { key: 'simply', label: 'Simply Orange', emoji: '🍊', search: 'Simply Orange juice' },
  { key: 'lacroix', label: 'LaCroix', emoji: '💧', search: 'LaCroix sparkling water' },
  { key: 'liquid_iv', label: 'Liquid I.V.', emoji: '💧', search: 'Liquid IV hydration' },
  // Cereal & Breakfast
  { key: 'kelloggs', label: "Kellogg's", emoji: '🥣', search: "Kellogg's cereal" },
  { key: 'general_mills', label: 'General Mills', emoji: '🥣', search: 'General Mills cereal' },
  { key: 'post', label: 'Post', emoji: '🥣', search: 'Post cereal' },
  { key: 'quaker', label: 'Quaker', emoji: '🌾', search: 'Quaker oats oatmeal' },
  // Snacks & Chips
  { key: 'frito_lay', label: 'Frito-Lay', emoji: '🥔', search: 'Frito-Lay variety snacks' },
  { key: 'lays', label: "Lay's", emoji: '🥔', search: "Lay's potato chips" },
  { key: 'doritos', label: 'Doritos', emoji: '🌽', search: 'Doritos tortilla chips' },
  { key: 'pringles', label: 'Pringles', emoji: '🥫', search: 'Pringles crisps' },
  { key: 'cheetos', label: 'Cheetos', emoji: '🧡', search: 'Cheetos puffed snacks' },
  { key: 'tostitos', label: 'Tostitos', emoji: '🌮', search: 'Tostitos tortilla chips salsa' },
  { key: 'skinny_pop', label: 'SkinnyPop', emoji: '🍿', search: 'SkinnyPop popcorn' },
  { key: 'clif', label: 'Clif Bar', emoji: '🏔️', search: 'Clif Bar energy snacks' },
  { key: 'kind', label: 'KIND', emoji: '🌰', search: 'KIND bars snacks' },
  // Cookies & Sweets
  { key: 'oreo', label: 'Oreo', emoji: '🍪', search: 'Oreo cookies' },
  { key: 'chips_ahoy', label: 'Chips Ahoy', emoji: '🍪', search: 'Chips Ahoy cookies' },
  { key: 'pepperidge_farm', label: 'Pepperidge Farm', emoji: '🌾', search: 'Pepperidge Farm cookies Goldfish' },
  { key: 'keebler', label: 'Keebler', emoji: '🧝', search: 'Keebler cookies crackers' },
  { key: 'little_debbie', label: 'Little Debbie', emoji: '👧', search: 'Little Debbie snack cakes' },
  { key: 'hostess', label: 'Hostess', emoji: '🎂', search: 'Hostess Twinkies cakes' },
  { key: 'breyers', label: 'Breyers', emoji: '🍦', search: 'Breyers ice cream' },
  { key: 'ben_jerrys', label: "Ben & Jerry's", emoji: '🍨', search: "Ben and Jerry's ice cream" },
  { key: 'haagen_dazs', label: 'Häagen-Dazs', emoji: '🍧', search: 'Haagen-Dazs ice cream' },
  // Candy
  { key: 'mars', label: 'Mars (Snickers, M&Ms)', emoji: '🍫', search: 'Mars candy Snickers M&Ms' },
  { key: 'hersheys', label: "Hershey's", emoji: '🍫', search: "Hershey's chocolate candy" },
  { key: 'reeses', label: "Reese's", emoji: '🥜', search: "Reese's peanut butter cups" },
  { key: 'haribo', label: 'Haribo', emoji: '🐻', search: 'Haribo gummy bears candy' },
  { key: 'skittles', label: 'Skittles', emoji: '🌈', search: 'Skittles candy' },
  { key: 'ghirardelli', label: 'Ghirardelli', emoji: '🍫', search: 'Ghirardelli chocolate squares' },
  { key: 'lindt', label: 'Lindt', emoji: '🍫', search: 'Lindt Excellence chocolate' },
  // Dairy & Eggs
  { key: 'kraft', label: 'Kraft', emoji: '🧀', search: 'Kraft cheese singles' },
  { key: 'philadelphia', label: 'Philadelphia', emoji: '🧀', search: 'Philadelphia cream cheese' },
  { key: 'sargento', label: 'Sargento', emoji: '🧀', search: 'Sargento shredded cheese' },
  { key: 'tillamook', label: 'Tillamook', emoji: '🧀', search: 'Tillamook cheddar cheese' },
  { key: 'chobani', label: 'Chobani', emoji: '🫙', search: 'Chobani Greek yogurt' },
  { key: 'fage', label: 'Fage', emoji: '🫙', search: 'Fage Greek yogurt' },
  { key: 'oatly', label: 'Oatly', emoji: '🥛', search: 'Oatly oat milk' },
  { key: 'land_o_lakes', label: 'Land O\' Lakes', emoji: '🧈', search: 'Land O Lakes butter dairy' },
  // Meat & Deli
  { key: 'oscar_mayer', label: 'Oscar Mayer', emoji: '🥓', search: 'Oscar Mayer bacon hot dogs' },
  { key: 'tyson', label: 'Tyson', emoji: '🍗', search: 'Tyson chicken products' },
  { key: 'perdue', label: 'Perdue', emoji: '🍗', search: 'Perdue chicken' },
  { key: 'jennie_o', label: 'Jennie-O', emoji: '🦃', search: 'Jennie-O turkey ground' },
  { key: 'ball_park', label: 'Ball Park', emoji: '⚾', search: 'Ball Park beef hot dogs' },
  { key: 'hillshire', label: 'Hillshire Farm', emoji: '🌭', search: 'Hillshire Farm smoked sausage' },
  { key: 'jimmy_dean', label: 'Jimmy Dean', emoji: '🍳', search: 'Jimmy Dean breakfast sausage' },
  { key: 'boars_head', label: "Boar's Head", emoji: '🥩', search: "Boar's Head deli meats" },
  { key: 'hormel', label: 'Hormel', emoji: '🥫', search: 'Hormel chili Spam products' },
  // Bread
  { key: 'daves_killer', label: "Dave's Killer Bread", emoji: '🍞', search: "Dave's Killer Bread" },
  { key: 'natures_own', label: "Nature's Own", emoji: '🍞', search: "Nature's Own bread" },
  { key: 'sara_lee', label: 'Sara Lee', emoji: '🍞', search: 'Sara Lee bread' },
  { key: 'mission', label: 'Mission', emoji: '🌮', search: 'Mission tortillas wraps' },
  { key: 'pepperidge', label: 'Pepperidge Farm Bread', emoji: '🥖', search: 'Pepperidge Farm bread rolls' },
  // Canned & Pantry
  { key: 'campbells', label: "Campbell's", emoji: '🥫', search: "Campbell's soup" },
  { key: 'progresso', label: 'Progresso', emoji: '🥫', search: 'Progresso soup' },
  { key: 'hunts', label: "Hunt's", emoji: '🍅', search: "Hunt's tomato sauce products" },
  { key: 'del_monte', label: 'Del Monte', emoji: '🥫', search: 'Del Monte canned vegetables fruits' },
  { key: 'starkist', label: 'StarKist', emoji: '🐟', search: 'StarKist tuna canned' },
  { key: 'jif', label: 'Jif', emoji: '🥜', search: 'Jif peanut butter' },
  { key: 'skippy', label: 'Skippy', emoji: '🥜', search: 'Skippy peanut butter' },
  { key: 'smuckers', label: "Smucker's", emoji: '🍓', search: "Smucker's jam jelly preserves" },
  { key: 'goya', label: 'Goya', emoji: '🌶️', search: 'Goya beans seasonings Latin foods' },
  { key: 'amy_organics', label: "Amy's Organic", emoji: '🌿', search: "Amy's organic foods" },
  { key: 'prego', label: 'Prego', emoji: '🍝', search: 'Prego pasta sauce' },
  { key: 'ragu', label: 'Ragú', emoji: '🍝', search: 'Ragu pasta sauce' },
  { key: 'raos', label: "Rao's Homemade", emoji: '🍝', search: "Rao's marinara pasta sauce" },
  // Pasta & Grains
  { key: 'barilla', label: 'Barilla', emoji: '🍝', search: 'Barilla pasta' },
  { key: 'ronzoni', label: 'Ronzoni', emoji: '🍝', search: 'Ronzoni pasta' },
  // Condiments
  { key: 'heinz', label: 'Heinz', emoji: '🍅', search: 'Heinz ketchup condiments' },
  { key: 'hellmanns', label: "Hellmann's", emoji: '🥗', search: "Hellmann's mayonnaise" },
  { key: 'dukes', label: "Duke's Mayo", emoji: '🥗', search: "Duke's mayonnaise" },
  { key: 'hidden_valley', label: 'Hidden Valley', emoji: '🥗', search: 'Hidden Valley Ranch dressing' },
  { key: 'sweet_baby_rays', label: "Sweet Baby Ray's", emoji: '🍖', search: "Sweet Baby Ray's barbecue sauce" },
  { key: 'franks', label: "Frank's RedHot", emoji: '🌶️', search: "Frank's RedHot hot sauce" },
  { key: 'kikkoman', label: 'Kikkoman', emoji: '🫙', search: 'Kikkoman soy sauce teriyaki' },
  { key: 'vlasic', label: 'Vlasic', emoji: '🥒', search: 'Vlasic pickles' },
  { key: 'old_el_paso', label: 'Old El Paso', emoji: '🌮', search: 'Old El Paso taco products' },
  { key: 'mccormick', label: 'McCormick', emoji: '🌿', search: 'McCormick spices seasonings' },
  // Cleaning & Household
  { key: 'tide', label: 'Tide', emoji: '🧺', search: 'Tide laundry detergent pods' },
  { key: 'gain', label: 'Gain', emoji: '🧺', search: 'Gain laundry detergent' },
  { key: 'dawn', label: 'Dawn', emoji: '🫧', search: 'Dawn dish soap' },
  { key: 'cascade', label: 'Cascade', emoji: '🫧', search: 'Cascade dishwasher pods' },
  { key: 'bounty', label: 'Bounty', emoji: '🧻', search: 'Bounty paper towels' },
  { key: 'charmin', label: 'Charmin', emoji: '🧻', search: 'Charmin toilet paper' },
  { key: 'kleenex', label: 'Kleenex', emoji: '🤧', search: 'Kleenex facial tissues' },
  { key: 'clorox', label: 'Clorox', emoji: '🧼', search: 'Clorox disinfecting wipes bleach' },
  { key: 'lysol', label: 'Lysol', emoji: '🧼', search: 'Lysol disinfectant spray wipes' },
  { key: 'swiffer', label: 'Swiffer', emoji: '🧹', search: 'Swiffer sweeper mop' },
  { key: 'glad', label: 'Glad', emoji: '🗑️', search: 'Glad trash bags containers' },
  { key: 'ziploc', label: 'Ziploc', emoji: '🗂️', search: 'Ziploc bags containers' },
  { key: 'reynolds', label: 'Reynolds Wrap', emoji: '🌀', search: 'Reynolds Wrap aluminum foil parchment' },
  // Personal Care
  { key: 'dove', label: 'Dove', emoji: '🕊️', search: 'Dove soap shampoo body wash' },
  { key: 'old_spice', label: 'Old Spice', emoji: '🧴', search: 'Old Spice deodorant body wash' },
  { key: 'head_shoulders', label: 'Head & Shoulders', emoji: '🧴', search: 'Head and Shoulders shampoo' },
  { key: 'pantene', label: 'Pantene', emoji: '🧴', search: 'Pantene shampoo conditioner' },
  { key: 'colgate', label: 'Colgate', emoji: '🦷', search: 'Colgate toothpaste' },
  { key: 'crest', label: 'Crest', emoji: '🦷', search: 'Crest toothpaste whitening' },
  { key: 'sensodyne', label: 'Sensodyne', emoji: '🦷', search: 'Sensodyne sensitive toothpaste' },
  { key: 'gillette', label: 'Gillette', emoji: '🪒', search: 'Gillette razor shaving' },
  { key: 'cerave', label: 'CeraVe', emoji: '🧴', search: 'CeraVe moisturizer face wash' },
  { key: 'neutrogena', label: 'Neutrogena', emoji: '🧴', search: 'Neutrogena face wash skincare' },
  { key: 'purell', label: 'Purell', emoji: '💧', search: 'Purell hand sanitizer' },
  // Baby
  { key: 'pampers', label: 'Pampers', emoji: '👶', search: 'Pampers diapers wipes' },
  { key: 'huggies', label: 'Huggies', emoji: '👶', search: 'Huggies diapers baby wipes' },
  { key: 'gerber', label: 'Gerber', emoji: '🍼', search: 'Gerber baby food formula' },
  { key: 'enfamil', label: 'Enfamil', emoji: '🍼', search: 'Enfamil baby formula' },
  // Pet
  { key: 'purina', label: 'Purina', emoji: '🐾', search: 'Purina dog cat food' },
  { key: 'blue_buffalo', label: 'Blue Buffalo', emoji: '🐶', search: 'Blue Buffalo natural pet food' },
  { key: 'pedigree', label: 'Pedigree', emoji: '🐕', search: 'Pedigree dog food' },
  { key: 'fancy_feast', label: 'Fancy Feast', emoji: '🐱', search: 'Fancy Feast wet cat food' },
  // Health
  { key: 'tylenol', label: 'Tylenol', emoji: '💊', search: 'Tylenol acetaminophen pain relief' },
  { key: 'advil', label: 'Advil', emoji: '💊', search: 'Advil ibuprofen pain reliever' },
  { key: 'vicks', label: 'Vicks', emoji: '🤧', search: 'Vicks NyQuil DayQuil cold flu' },
  { key: 'claritin', label: 'Claritin', emoji: '🌸', search: 'Claritin allergy relief' },
  { key: 'centrum', label: 'Centrum', emoji: '💊', search: 'Centrum vitamins supplements' },
  // Misc Grocery
  { key: 'birds_eye', label: "Bird's Eye", emoji: '🥦', search: "Bird's Eye frozen vegetables" },
  { key: 'green_giant', label: 'Green Giant', emoji: '🌽', search: 'Green Giant frozen canned vegetables' },
  { key: 'pillsbury', label: 'Pillsbury', emoji: '🎂', search: 'Pillsbury dough baking mixes' },
  { key: 'betty_crocker', label: 'Betty Crocker', emoji: '🎂', search: 'Betty Crocker cake mix frosting' },
  { key: 'duncan_hines', label: 'Duncan Hines', emoji: '🎂', search: 'Duncan Hines cake brownie mix' },
  { key: 'nestle', label: 'Nestlé', emoji: '🍫', search: "Nestle Toll House chocolate chips baking" },
];