export const ALL_STORES = [
  { key: 'kroger',        name: 'Kroger',           region: 'National',    color: 'blue' },
  { key: 'walmart',       name: 'Walmart',          region: 'National',    color: 'yellow' },
  { key: 'amazon',        name: 'Amazon Fresh',     region: 'National',    color: 'orange' },
  { key: 'aldi',          name: 'Aldi',             region: 'National',    color: 'teal' },
  { key: 'trader_joes',   name: "Trader Joe's",     region: 'National',    color: 'red' },
  { key: 'whole_foods',   name: 'Whole Foods',      region: 'National',    color: 'green' },
  { key: 'publix',        name: 'Publix',           region: 'Southeast',   color: 'emerald' },
  { key: 'safeway',       name: 'Safeway',          region: 'West/Mid',    color: 'cyan' },
  { key: 'albertsons',    name: 'Albertsons',       region: 'West',        color: 'purple' },
  { key: 'heb',           name: 'H-E-B',            region: 'Texas',       color: 'red' },
  { key: 'meijer',        name: 'Meijer',           region: 'Midwest',     color: 'indigo' },
  { key: 'hyvee',         name: 'Hy-Vee',           region: 'Midwest',     color: 'rose' },
  { key: 'fred_meyer',    name: 'Fred Meyer',       region: 'Northwest',   color: 'lime' },
  { key: 'fresh_market',  name: 'The Fresh Market', region: 'Southeast',   color: 'green' },
  { key: 'wegmans',       name: 'Wegmans',          region: 'Northeast',   color: 'orange' },
  { key: 'harris_teeter', name: 'Harris Teeter',    region: 'Southeast',   color: 'blue' },
  { key: 'food_lion',     name: 'Food Lion',        region: 'Southeast',   color: 'red' },
  { key: 'giant_eagle',   name: 'Giant Eagle',      region: 'Midwest/NE',  color: 'amber' },
  { key: 'stop_shop',     name: 'Stop & Shop',      region: 'Northeast',   color: 'cyan' },
  { key: 'jewel_osco',    name: 'Jewel-Osco',       region: 'Midwest',     color: 'purple' },
  { key: 'hannaford',     name: 'Hannaford',        region: 'Northeast',   color: 'teal' },
  { key: 'market_basket', name: 'Market Basket',    region: 'Northeast',   color: 'indigo' },
  { key: 'smiths',        name: "Smith's",          region: 'West',        color: 'emerald' },
  { key: 'acme',          name: 'Acme Markets',     region: 'Northeast',   color: 'rose' },
  { key: 'iga',           name: 'IGA',              region: 'National',    color: 'red' },
  { key: 'king_soopers',  name: 'King Soopers',     region: 'Colorado',    color: 'blue' },
  { key: 'city_market',   name: 'City Market',      region: 'Colorado',    color: 'green' },
  { key: 'rouses',        name: 'Rouses',           region: 'Gulf South',  color: 'amber' },
  { key: 'stater_bros',   name: 'Stater Bros',      region: 'So Cal',      color: 'orange' },
  { key: 'bristol_farms', name: 'Bristol Farms',    region: 'So Cal',      color: 'lime' },
  { key: 'gelsons',       name: "Gelson's",         region: 'So Cal',      color: 'purple' },
  { key: 'frys',          name: "Fry's Food",       region: 'Arizona',     color: 'red' },
  { key: 'piggly_wiggly', name: 'Piggly Wiggly',   region: 'Southeast',   color: 'pink' },
  { key: 'hornbachers',   name: "Hornbacher's",     region: 'Midwest',     color: 'cyan' },
  { key: 'big_y',         name: 'Big Y',            region: 'Northeast',   color: 'indigo' },
  { key: 'stew_leonards', name: "Stew Leonard's",   region: 'Northeast',   color: 'emerald' },
  { key: 'detweilers',    name: "Detweiler's",      region: 'Mid-Atlantic',color: 'teal' },
  { key: 'foodland',      name: 'Foodland',         region: 'Hawaii',      color: 'amber' },
  { key: 'kta',           name: 'KTA Super Stores', region: 'Hawaii',      color: 'orange' },
];

// Color palette per tailwind color name
export const COLOR_MAP = {
  blue:    { badge: 'bg-blue-100 text-blue-700 border-blue-200',    bar: 'from-blue-500 to-blue-600',     light: 'bg-blue-50',    border: 'border-blue-200',   shadow: 'shadow-blue-100'  },
  yellow:  { badge: 'bg-amber-100 text-amber-700 border-amber-200', bar: 'from-amber-400 to-yellow-500',  light: 'bg-amber-50',   border: 'border-amber-200',  shadow: 'shadow-amber-100' },
  orange:  { badge: 'bg-orange-100 text-orange-700 border-orange-200', bar: 'from-orange-500 to-orange-600', light: 'bg-orange-50', border: 'border-orange-200', shadow: 'shadow-orange-100' },
  teal:    { badge: 'bg-teal-100 text-teal-700 border-teal-200',    bar: 'from-teal-500 to-teal-600',     light: 'bg-teal-50',    border: 'border-teal-200',   shadow: 'shadow-teal-100'  },
  red:     { badge: 'bg-red-100 text-red-700 border-red-200',       bar: 'from-red-500 to-red-600',       light: 'bg-red-50',     border: 'border-red-200',    shadow: 'shadow-red-100'   },
  green:   { badge: 'bg-green-100 text-green-700 border-green-200', bar: 'from-green-500 to-green-600',   light: 'bg-green-50',   border: 'border-green-200',  shadow: 'shadow-green-100' },
  emerald: { badge: 'bg-emerald-100 text-emerald-700 border-emerald-200', bar: 'from-emerald-500 to-emerald-600', light: 'bg-emerald-50', border: 'border-emerald-200', shadow: 'shadow-emerald-100' },
  cyan:    { badge: 'bg-cyan-100 text-cyan-700 border-cyan-200',    bar: 'from-cyan-500 to-cyan-600',     light: 'bg-cyan-50',    border: 'border-cyan-200',   shadow: 'shadow-cyan-100'  },
  purple:  { badge: 'bg-purple-100 text-purple-700 border-purple-200', bar: 'from-purple-500 to-purple-600', light: 'bg-purple-50', border: 'border-purple-200', shadow: 'shadow-purple-100' },
  indigo:  { badge: 'bg-indigo-100 text-indigo-700 border-indigo-200', bar: 'from-indigo-500 to-indigo-600', light: 'bg-indigo-50', border: 'border-indigo-200', shadow: 'shadow-indigo-100' },
  rose:    { badge: 'bg-rose-100 text-rose-700 border-rose-200',    bar: 'from-rose-500 to-rose-600',     light: 'bg-rose-50',    border: 'border-rose-200',   shadow: 'shadow-rose-100'  },
  lime:    { badge: 'bg-lime-100 text-lime-700 border-lime-200',    bar: 'from-lime-500 to-lime-600',     light: 'bg-lime-50',    border: 'border-lime-200',   shadow: 'shadow-lime-100'  },
  amber:   { badge: 'bg-amber-100 text-amber-700 border-amber-200', bar: 'from-amber-500 to-amber-600',   light: 'bg-amber-50',   border: 'border-amber-200',  shadow: 'shadow-amber-100' },
  pink:    { badge: 'bg-pink-100 text-pink-700 border-pink-200',    bar: 'from-pink-500 to-pink-600',     light: 'bg-pink-50',    border: 'border-pink-200',   shadow: 'shadow-pink-100'  },
};

export function getStoreByKey(key) {
  return ALL_STORES.find(s => s.key === key);
}