// Deep links / signup URLs for grocery stores
export const STORE_LINKS = {
  kroger:        { website: 'https://www.kroger.com', signup: 'https://www.kroger.com/account/create', app_ios: 'https://apps.apple.com/us/app/kroger/id403901186', app_android: 'https://play.google.com/store/apps/details?id=com.kroger.mobile', loyalty: true, loyalty_label: 'Kroger Plus Card #' },
  walmart:       { website: 'https://www.walmart.com', signup: 'https://www.walmart.com/account/signup', app_ios: 'https://apps.apple.com/us/app/walmart-shopping-grocery/id338137227', app_android: 'https://play.google.com/store/apps/details?id=com.walmart.android', loyalty: false },
  amazon:        { website: 'https://www.amazon.com/fresh', signup: 'https://www.amazon.com/ap/register', app_ios: 'https://apps.apple.com/us/app/amazon-shopping/id297606951', app_android: 'https://play.google.com/store/apps/details?id=com.amazon.mShop.android.shopping', loyalty: false },
  aldi:          { website: 'https://www.aldi.us', signup: 'https://www.aldi.us/en/myaldi/', app_ios: 'https://apps.apple.com/us/app/aldi/id1137512002', app_android: 'https://play.google.com/store/apps/details?id=com.aldi.aldius', loyalty: false },
  trader_joes:   { website: 'https://www.traderjoes.com', signup: null, app_ios: null, app_android: null, loyalty: false },
  whole_foods:   { website: 'https://www.wholefoodsmarket.com', signup: 'https://www.amazon.com/ap/register', app_ios: 'https://apps.apple.com/us/app/whole-foods-market/id1062432583', app_android: 'https://play.google.com/store/apps/details?id=com.wholefoods.wholefoodsmarket', loyalty: false },
  publix:        { website: 'https://www.publix.com', signup: 'https://www.publix.com/myaccount/register', app_ios: 'https://apps.apple.com/us/app/publix/id451189682', app_android: 'https://play.google.com/store/apps/details?id=com.publix.mobile', loyalty: true, loyalty_label: 'Publix Club Card #' },
  safeway:       { website: 'https://www.safeway.com', signup: 'https://www.safeway.com/account/create-profile.html', app_ios: 'https://apps.apple.com/us/app/safeway-deals-delivery/id331357928', app_android: 'https://play.google.com/store/apps/details?id=com.safeway.client.android.safeway', loyalty: true, loyalty_label: 'Safeway Club Card #' },
  albertsons:    { website: 'https://www.albertsons.com', signup: 'https://www.albertsons.com/account/create-profile.html', app_ios: 'https://apps.apple.com/us/app/albertsons-deals-delivery/id1030764302', app_android: 'https://play.google.com/store/apps/details?id=com.albertsons.client.android', loyalty: true, loyalty_label: 'Albertsons for U Card #' },
  heb:           { website: 'https://www.heb.com', signup: 'https://www.heb.com/account-info/create-account', app_ios: 'https://apps.apple.com/us/app/h-e-b/id728416939', app_android: 'https://play.google.com/store/apps/details?id=com.heb.app', loyalty: false },
  meijer:        { website: 'https://www.meijer.com', signup: 'https://www.meijer.com/registration.html', app_ios: 'https://apps.apple.com/us/app/meijer/id491591684', app_android: 'https://play.google.com/store/apps/details?id=com.meijer.android', loyalty: true, loyalty_label: 'mPerks Card #' },
  hyvee:         { website: 'https://www.hy-vee.com', signup: 'https://www.hy-vee.com/my-account/create-account', app_ios: 'https://apps.apple.com/us/app/hy-vee-aisles-online/id780390906', app_android: 'https://play.google.com/store/apps/details?id=com.hyvee.grocery', loyalty: true, loyalty_label: 'Hy-Vee Fuel Saver #' },
  wegmans:       { website: 'https://www.wegmans.com', signup: 'https://www.wegmans.com/register/', app_ios: 'https://apps.apple.com/us/app/wegmans/id388083953', app_android: 'https://play.google.com/store/apps/details?id=com.wegmans.wegmansapp', loyalty: true, loyalty_label: 'Wegmans Shoppers Club #' },
  harris_teeter: { website: 'https://www.harristeeter.com', signup: 'https://www.harristeeter.com/account/create-profile.html', app_ios: 'https://apps.apple.com/us/app/harris-teeter/id506764459', app_android: 'https://play.google.com/store/apps/details?id=com.harristeeter.client.android', loyalty: true, loyalty_label: 'VIC Card #' },
  food_lion:     { website: 'https://www.foodlion.com', signup: 'https://www.foodlion.com/account/register', app_ios: 'https://apps.apple.com/us/app/food-lion/id528463987', app_android: 'https://play.google.com/store/apps/details?id=com.foodlion.mobile', loyalty: true, loyalty_label: 'MVP Card #' },
  giant_eagle:   { website: 'https://www.gianteagle.com', signup: 'https://www.gianteagle.com/account/register', app_ios: 'https://apps.apple.com/us/app/giant-eagle/id376750699', app_android: 'https://play.google.com/store/apps/details?id=com.gianteagle.mobileapp', loyalty: true, loyalty_label: 'Advantage Card #' },
  stop_shop:     { website: 'https://stopandshop.com', signup: 'https://stopandshop.com/pages/create-account', app_ios: 'https://apps.apple.com/us/app/stop-shop/id408286793', app_android: 'https://play.google.com/store/apps/details?id=com.stopandshop.mobile', loyalty: true, loyalty_label: 'Go Rewards Card #' },
  jewel_osco:    { website: 'https://www.jewelosco.com', signup: 'https://www.jewelosco.com/account/create-profile.html', app_ios: 'https://apps.apple.com/us/app/jewel-osco-deals-delivery/id504417919', app_android: 'https://play.google.com/store/apps/details?id=com.jewelosco.client.android', loyalty: true, loyalty_label: 'Jewel-Osco Card #' },
  king_soopers:  { website: 'https://www.kingsoopers.com', signup: 'https://www.kingsoopers.com/account/create', app_ios: 'https://apps.apple.com/us/app/king-soopers/id402978346', app_android: 'https://play.google.com/store/apps/details?id=com.kingsoopers.mobile', loyalty: true, loyalty_label: 'King Soopers Card #' },
  fred_meyer:    { website: 'https://www.fredmeyer.com', signup: 'https://www.fredmeyer.com/account/create', app_ios: 'https://apps.apple.com/us/app/fred-meyer/id402954519', app_android: 'https://play.google.com/store/apps/details?id=com.fredmeyer.mobile', loyalty: true, loyalty_label: 'Fred Meyer Rewards #' },
};

export function getStoreLink(key) {
  return STORE_LINKS[key] || { website: null, signup: null, app_ios: null, app_android: null, loyalty: false };
}